Tabs
dialpad/dialtone-legacy pull request #102
Opened 2020-08-20 19:16 UTC by hynes-dialpad

This add tab styles into Dialtone. I've provided HTML ARIA role and accessibility items to tabs as well.

![image](https://user-images.githubusercontent.com/44445385/90814905-d1084100-e2f7-11ea-98fc-8943276ea26d.png)

## To-do:
- [x] Finish tab description
- [x] Add ARIA / Accessibility information
- [x] Simple JS to hook up examples 😎

2020-08-20 20:32 UTC, tedgoas-dialpad requested changes

2020-08-20 20:32 UTC, tedgoas-dialpad commented on docs/_includes/head.html
> +    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
What is this for?

2020-08-20 20:32 UTC, tedgoas-dialpad commented on docs/assets/less/dialtone-docs.less
> +@define-font-name:              "Roboto", @font-family--sans;
Should we be doing this in _this_ PR?

2020-08-20 20:32 UTC, tedgoas-dialpad commented on lib/build/less/components/tabs.less
> +        border-radius: @spacing4 @spacing4 0 0;
It's a personal preference, but this part is throwing me off visually. I'm just like... "why?"

2020-08-20 20:32 UTC, tedgoas-dialpad commented on lib/build/less/components/tabs.less
> +        height: @spacing4;
Tried halving this to 2px and no border radius 🤷‍♀️ Again, personal preference but I like it. Feels more crisp.

<img width="344" alt="Screen Shot 2020-08-20 at 4 25 24 PM" src="https://user-images.githubusercontent.com/65190890/90822096-eda97680-e301-11ea-8088-2d5329db10da.png">

2020-08-20 20:32 UTC, tedgoas-dialpad commented on lib/build/less/components/tabs.less
> +
We may want a `cursor: pointer` here or the dialtone equivalent. I wasn't getting any visual indication these are clickable on `:hover`.

2020-08-20 20:32 UTC, tedgoas-dialpad commented on lib/build/less/components/tabs.less
> +    @media (prefers-reduced-motion) {
I wonder if we could put this in a more global location so that we don't have to redefine it for each component.

2020-08-20 20:32 UTC, tedgoas-dialpad commented on docs/components/tabs.html
> +</section>
Do we want to add a section for responsive? Eg. What the "More" menu is invoked?

2020-08-20 20:32 UTC, tedgoas-dialpad commented on docs/components/tabs.html
> +<section class="dialtone-section8">
Do we want to include a Do's and Don'ts section here to advise folks when to use tabs and when "just add another tab" isn't appropriate?

2020-08-21 17:37 UTC, hynes-dialpad commented on lib/build/less/components/tabs.less
> +    @media (prefers-reduced-motion) {
Possibly. I'd rather look at doing a universal selector like that in a separate PR. For now, we can at least do it here.

2020-08-28 14:24 UTC, hynes-dialpad commented on docs/components/tabs.html
> +</section>
I'm going to push this to a future iteration as it will require some JS work.

2020-08-28 14:25 UTC, hynes-dialpad commented on docs/components/tabs.html
> +<section class="dialtone-section8">
Probably, but we need to do this for all components. I'd rather tackle it then.

2020-08-28 23:04 UTC, dbecherdialpad approved these changes

2020-09-09 21:18 UTC, tedgoas-dialpad commented
@hynes-dialpad We spoke about tab width. (I think) we agreed to make the tabs less wide by default and adding modifiers to make them wider and include an underline. Something like:

`d-tablist`(Narrow width, no underline)
`d-tablist d-tablist__wide`
`d-tablist d-tablist__underline`

2020-09-30 12:30 UTC, closed without merging