Add flexbox utility classes
dialpad/dialtone-legacy pull request #107
Opened 2020-08-27 19:23 UTC by tedgoas-dialpad

This adds more utility classes for common flexbox properties:

- [ ] Justify Content
- [ ] Align Items
- [ ] Align Content
- [ ] Align Self
- [ ] Flex Flow (docs only)

Part of #101

2020-08-30 01:50 UTC, hynes-dialpad requested changes
A few more items we should add:

- Flex Direction
- Flex Wrap
- `unset` options for each utility class.

Here's a Less Flex utility file that used to be in Dialtone that we could re-add: https://github.com/dialpad/dialtone/blob/v2.0.0/lib/less/utilities/flex.less

2020-08-30 01:51 UTC, hynes-dialpad commented on lib/build/less/utilities/flex.less
> +.d-row-wrap              { flex-flow: row wrap !important; }
These utilities don't follow the same pattern as all the other utilities. These should probably be `d-ff-row-nowrap`, etc.

2020-08-31 14:04 UTC, tedgoas-dialpad commented on lib/build/less/utilities/flex.less
> +.d-row-wrap              { flex-flow: row wrap !important; }
Good call, updated.

2020-08-31 14:18 UTC, tedgoas-dialpad commented on lib/build/less/utilities/flex.less
> +.d-flex             { display: flex; }
@hynes-dialpad Adding utility classes here, but leaving `display: flex;` inside `.d-flex-columns` for now since I don't know what will break if we remove it.

2020-08-31 14:24 UTC, tedgoas-dialpad commented
@hynes-dialpad 

> A few more items we should add:
> * Flex Direction
> * Flex Wrap

We have classes for `flex-flow`, which is shorthand for `flex-direction` and `flex-wrap`. Seems to cover all the cases. Good enough?

2020-09-01 19:19 UTC, dbecherdialpad approved these changes

2020-09-09 20:32 UTC, hynes-dialpad approved these changes

2020-09-21 17:58 UTC, merged