Add utility classes for Display
dialpad/dialtone-legacy pull request #109
Opened 2020-08-27 21:35 UTC by tedgoas-dialpad

Adds variables and utility classes for the `display` property.

- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]

2020-08-28 21:59 UTC, dbecherdialpad reviewed
We probably want to include inline-flex and inline-grid, maybe as modifiers for the existing flex and grid utilities. We would need all the table ones if we include `display: table` but I'm not convinced we need to include that one.

2020-08-28 21:59 UTC, dbecherdialpad commented on docs/_data/display.json
> +    "output": "display: unset;"
imo these names are a bit too terse, `.d-none` sounds like it could refer to a lot of things

2020-08-30 01:58 UTC, hynes-dialpad requested changes

2020-08-30 01:58 UTC, hynes-dialpad commented on lib/build/less/utilities/display.less
> +.d-block          { display: @d-block !important; }
These utility classes should include the CSS abbreviation even though it would be a little repetitious. Instead of `d-block`, let's do `d-d-block`.

These classes used to be in Dialtone. You can view them here: https://github.com/dialpad/dialtone/blob/v2.0.0/lib/less/utilities/layout.less

2020-08-30 01:58 UTC, hynes-dialpad commented on lib/build/less/variables/display.less
> +@d-block:         block;
Why do we need variables for display?

2020-08-31 14:56 UTC, tedgoas-dialpad commented on docs/_data/display.json
> +    "output": "display: unset;"
Yea, Hynes made a similar comment. I'll update.

2020-08-31 15:36 UTC, tedgoas-dialpad commented
> We would need all the table ones if we include display: table but I'm not convinced we need to include that one.

[I removed all `table` classes](https://github.com/dialpad/dialtone/pull/109/commits/d244e5d0ed4bf39bffaee2e3559efaad1d6ac50f) because any problems they'd solved would likely be solved by using Flexbox, Grid, or semantic table markup.

cc @dbecherdialpad

2020-08-31 15:38 UTC, tedgoas-dialpad commented on lib/build/less/variables/display.less
> +@d-block:         block;
No, we really don't. I put them in so folks wouldn't have to type `block` or `inline` but it doesn't save any time or fix any issues. I'll remove.

2020-08-31 18:29 UTC, dbecherdialpad approved these changes

2020-09-09 20:31 UTC, hynes-dialpad approved these changes

2020-09-21 17:52 UTC, merged