Margin & Padding Utility Classes
dialpad/dialtone-legacy pull request #123
Opened 2020-09-30 21:34 UTC by hynes-dialpad

## Checklist
 - [x] Have you asked the contributors if a similar effort is already in process or has been solved?
 - [x] You've reviewed the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md)?
 - [x] Your pull request uses `staging` as its base branch. (All PRs using `production` as its base branch will be declined).
 - [x] All `gulp` scripts successfully compile.
 - [x] Any affected documentation has been updated, removed, or extended.
 - [x] Provide a description what is being changed, extended, or removed.
 - [x] Link to any issue(s) this request is resolving.
 - [x] Request a review from Joshua Hynes, Ted Goas, or David Becher.

### Description
Add immutable margin and padding classes and update the documentation accordingly. This keeps all pre-existing `d-margin[-dir][#][--negative]` and  `d-padding[-dir][#]`, but adds immutable margin (`.d-m[t|r|b|l][n][#]`) and padding (`.d-p[t|r|b|l][#]`). It also updates the auto margin classes in the same way and adds in margin and padding reset classes.

Also the documentation has been updated to better illustrate what these classes do.

This PR helps us with #101 .

2020-10-01 13:51 UTC, tedgoas-dialpad requested changes
Left a bunch of small suggestions on how to streamline the documentation. The LESS looks solid 🦾

2020-10-01 13:51 UTC, tedgoas-dialpad commented on docs/utilities/layout/margin.html
> +    <p class="dialtone-copy__normal">Starting in v5.9.0, Dialtone began providing immutable margin classes, meaning they include an <span class="code-example--inline">!important</span> to override CS
"Starting in v5.9.0, Dialtone offers immutable margin classes..."

A bit more succinct.

2020-10-01 13:51 UTC, tedgoas-dialpad commented on docs/utilities/layout/margin.html
> +    <p class="dialtone-copy__normal">The margin utility classes are provided to help visually separate elements. Because the desired visual separation in layouts is highly contextual, margin is never
This paragraph could be reworded. How about something like:

> The margin utility classes help visually separate elements. Margin should never applied to a component's outer wrapper, though it can be used on elements inside the component.

2020-10-01 13:51 UTC, tedgoas-dialpad commented on docs/utilities/layout/margin.html
> -                                <th scope="row">.d-margin{% if i != "All" %}-{{ i }}{% endif %}{{ val }}</th>
Do we need a `Direction` column here? Should be pretty easy to tell from the class names, output, and examples... no?

2020-10-01 13:51 UTC, tedgoas-dialpad commented on docs/utilities/layout/margin.html
> -<div class=".d-margin8">...</div>
These `...` should be `…` 👮‍♂️

2020-10-01 13:51 UTC, tedgoas-dialpad commented on docs/utilities/layout/margin.html
> -                            <th scope="row">.d-margin{% if i != "All" %}-{{ i }}{% endif %}{{ val }}--negative</th>
Same comment about needing a direction column.

2020-10-01 13:51 UTC, tedgoas-dialpad commented on docs/utilities/layout/margin.html
> +<div class="d-mn8">...</div>
Same comments about making these `...` a `…`/.

2020-10-01 13:51 UTC, tedgoas-dialpad commented on docs/utilities/layout/margin.html
> -<div class=".d-margin--auto">...</div>
`…` 👮‍♂️

2020-10-01 13:51 UTC, tedgoas-dialpad commented on docs/utilities/layout/margin.html
> +        <p class="dialtone-copy__normal">Allows you to reset an element's margin to its initial value.</p>
> Unsetting margins resets an element's margin to its initial value.

This follows the sentence structure of the other sections.

2020-10-01 13:51 UTC, tedgoas-dialpad commented on docs/utilities/layout/margin.html
> +description: CSS property which allows you to adjust an element's exterior spacing between other objects.
"Utilities to adjust an element's exterior..." ?

2020-10-01 13:51 UTC, tedgoas-dialpad commented on docs/utilities/layout/padding.html
> +description: CSS property which allows you to adjust an element's interior spacing between its child elements and the element's box edge.
"Utilities to adjust an element's interior..." ?

2020-10-01 13:51 UTC, tedgoas-dialpad commented on docs/utilities/layout/padding.html
> +                    <th scope="col" class="d-width10">Direction</th>
Same comment here about needing a column for Direction.

2020-10-01 13:51 UTC, tedgoas-dialpad commented on docs/utilities/layout/padding.html
> +    <p class="dialtone-copy__normal">Components will typically set their own padding, which is preferred. However components should not create extranenous modifying classes for increasing padding whe
Feels like we're over-explaining things here. How about something like:

> Components typically set their own padding defaults. However these padding utilities can be used to override these defaults in one-off situations.

2020-10-01 13:51 UTC, tedgoas-dialpad commented on docs/utilities/layout/padding.html
> +        <p class="dialtone-copy__normal">Allows you to reset an element's padding to its initial value.</p>
> Unsetting padding resets an element's padding to its initial value.

This follows the sentence structure of the other sections.

2020-10-01 13:51 UTC, tedgoas-dialpad commented on docs/utilities/layout/padding.html
> +<div class="d-p8">...</div>
These `...` should be `…` 👮‍♂️

2020-10-01 13:51 UTC, tedgoas-dialpad commented on lib/build/less/utilities/margin.less
> +//  Older classes. Will be deprecated in a future version
Just clarifying, were these older classes just incorrect in Dialtone? We're not adding "new" old classes, right?

2020-10-01 13:51 UTC, tedgoas-dialpad commented on docs/utilities/layout/padding.html
> +                        <div class="d-fl-center d-width100 d-border d-border-color--navy-lighter d-fc-navy-text d-fs11 d-fw-bold d-ff-mono d-lh-tight d-background-color--navy-lightest">.d-p{% if i !=
Should the pink border be *inside* the purple box in this case? That it's on the outside leads me to believe this is `margin`.

2020-10-01 18:13 UTC, tedgoas-dialpad commented
@hynes-dialpad Also feels like a good time to fill out [the spacing variables section](https://dialpad.design/variables/spacing/) since it's referenced in these pages.

2020-10-01 23:04 UTC, hynes-dialpad commented on lib/build/less/utilities/margin.less
> +//  Older classes. Will be deprecated in a future version
This is just github acting up because the line numbers got moved around.

2020-10-02 12:24 UTC, tedgoas-dialpad submitted a review, later dismissed
Yea, looks great! I think we should prioritize [the spacing variables section](https://dialpad.design/variables/spacing/) since it's referenced in these pages, but we can do that in a separate PR.

Adding @dbecherdialpad as a third set of eyes, can you give a quick once-over?

2020-10-02 14:29 UTC, hynes-dialpad commented
@TedGoas Well I did a spacing variables page. It could probably use more, but it's a start.

2020-10-02 19:06 UTC, tedgoas-dialpad commented
@hynes-dialpad Nice, great start. We can always improve it later!

2020-10-02 19:08 UTC, tedgoas-dialpad approved these changes, later dismissed

2020-10-02 21:00 UTC, merged