Background Utility Classes
dialpad/dialtone-legacy pull request #126
Opened 2020-10-05 15:04 UTC by hynes-dialpad

# Description
Update background color utility classes to make them immutable and reflective of the new utility class naming approach. Also add in background gradients for use with our new label work:

![image](https://user-images.githubusercontent.com/44445385/95096558-6883f080-06fa-11eb-83fb-be5435ae644c.png)

# Checklist
 - [x] Have you asked the contributors if a similar effort is already in process or has been solved?
 - [x] You've reviewed the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md)?
 - [x] Your pull request uses `staging` as its base branch. (All PRs using `production` as its base branch will be declined).
 - [x] All `gulp` scripts successfully compile.
 - [ ] Any affected documentation has been updated, removed, or extended.
 - [ ] Provide a description what is being changed, extended, or removed.
 - [ ] Link to any issue(s) this request is resolving.
 - [ ] Request a review from Joshua Hynes, Ted Goas, or David Becher.

2020-10-07 19:39 UTC, tedgoas-dialpad requested changes
Couple bugs and a question about whether to offer opacity to background gradients.

2020-10-07 19:39 UTC, tedgoas-dialpad commented on docs/utilities/visual/background-gradients.html
> +<section class="d-stack16">
What's the use case for Opacity? We're already providing a lot of options to manipulate a gradient. Does this give folks enough rope to hang themselves with?

2020-10-07 19:39 UTC, tedgoas-dialpad commented on docs/utilities/visual/backgrounds.html
>              <h3 class="dialtone-title__subsection">{{ color.color }}</h3>
Some text contrast issues with the darker colors in this page:
<img width="1189" alt="Screen Shot 2020-10-07 at 3 27 27 PM" src="https://user-images.githubusercontent.com/65190890/95378862-87c57e00-08b2-11eb-85ee-fe0c97b133d8.png">

2020-10-07 19:39 UTC, tedgoas-dialpad commented on docs/utilities/visual/backgrounds.html
>  <section class="d-stack16">
Why are the swatches on [backgrounds](https://deploy-preview-126--dialtone.netlify.app/utilities/visual/backgrounds/) two column, but [background gradients](https://deploy-preview-126--dialtone.netlify.app/utilities/visual/background-gradients/) is three? Can we make them match?

1 vote for three column :)

2020-10-07 19:39 UTC, tedgoas-dialpad commented on docs/utilities/visual/background-gradients.html
> +            <div class="dialtone-color-grid__group">
If we keep this section, more contrast issues. Maybe align the text right?
<img width="765" alt="Screen Shot 2020-10-07 at 3 37 31 PM" src="https://user-images.githubusercontent.com/65190890/95379273-2a7dfc80-08b3-11eb-8d03-d9f5c21d4ed4.png">

2020-10-14 13:36 UTC, hynes-dialpad commented on docs/utilities/visual/background-gradients.html
> +<section class="d-stack16">
I'd rather default to providing more flexibility than less. If we're seeing misuse we can always pull back IMO.

2020-10-14 14:10 UTC, hynes-dialpad commented
@tedgoas-dialpad I've made the requested updates. If you could review and approve if you don't find anything else, that would be appreciated!

2020-10-14 20:37 UTC, merged