Adding brand icons to be used in Marketplace
dialpad/dialtone-legacy pull request #167
Opened 2021-01-28 20:13 UTC by vcheng-dialpad

## Description
Adding brand icons such as Airtable, Asana, Freshworks CRM, Greenhouse, Jira Service Desk, Monday.com, Pipedrive, Toggl, Zoho desk, Zoho

Not sure why the file `docs/assets/css/dialtone--syntax.css` is affected :/

## Pull Request Checklist

 - [ ] Ask the contributors if a similar effort is already in process or has been solved.
 - [ ] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [ ] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [ ] Ensure all `gulp` scripts successfully compile.
 - [ ] Update, remove, or extend all affected documentation.
 - [ ] Provide a description what is being changed, extended, or removed.
 - [ ] Link to any issue(s) this request is resolving.
 - [ ] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
 - [ ] Request a review from Joshua Hynes, Ted Goas, or David Becher.

2021-01-29 22:08 UTC, dialpad-drew reviewed
1. Were you hoping to display these on the doc site's "Brand Icons" page? I noticed they weren't added ([see Netlify](https://deploy-preview-167--dialtone.netlify.app/icons/brand/)).
2. Do the files' names fit into our existing naming patterns? I see existing files use lowercase and hyphenation (i.e. `zoho-desk` instead of `Zoho Desk`). We'll almost certainly want to avoid spaces in our URL patterns.

2021-01-29 22:08 UTC, dialpad-drew commented on .gitignore
> +lib/build/svg/brand/Airtable.png
I'm still not entirely familiar with this project, @vcheng-dialpad, but this strikes me as odd for these reasons:

1. Why would we ignore just these 10 Brand icons and not the others in that directory?
2. Provided a reason for the above, is this the proper place in `.gitignore` to declare them?

2021-01-29 22:34 UTC, hynes-dialpad requested changes
The items you removed the `.gitignore` file need removed.

2021-02-01 23:15 UTC, vcheng-dialpad commented on .gitignore
> +lib/build/svg/brand/Airtable.png
Initially I accidentally added the png files rather than the svg files, so I entered the `.gitignore` as it shows up as an option to delete the png files. Please let me know if what's the proper way of deleting icons!

2021-02-01 23:29 UTC, vcheng-dialpad commented
> 1. Were you hoping to display these on the doc site's "Brand Icons" page? I noticed they weren't added ([see Netlify](https://deploy-preview-167--dialtone.netlify.app/icons/brand/)).
> 2. Do the files' names fit into our existing naming patterns? I see existing files use lowercase and hyphenation. We'll almost certainly want to avoid spaces in our URL patterns. (i.e. `zoho-desk` instead of `Zoho Desk`)
> 3. Was your `staging` branch up-to-date when starting this branch? I'm noticing down-versioning in your `package-lock.json`.

@dialpad-drew 
1. Yes, I was, I thought that the icons did show up in the local host.
2. I'll rename the icons to match the current standard. 
3. I made sure to update the branch when I started staging, but now that you mentioned it, I am not too sure how to check if my branch is the most up-to-date or not

2021-02-01 23:31 UTC, dialpad-drew commented on .gitignore
> +lib/build/svg/brand/Airtable.png
@vcheng-dialpad Deleting files is real easy and is essentially the same process as adding files: 

1. Delete files locally on your working branch
2. Commit those changes
3. Push your branch

Easy as pie. Technically `git revert` is probably the "more right" way to do it, but it's a little more technical and the above is probably a little easier to learn while achieving essentially the same outcome.

For reference, `.gitignore` is a way to specify which files, file types, directories, etc. should be ignored and not tracked by git throughout the **entire project** on every branch.

If you run into any snags or have any questions, feel free to DM me and we can walk through it.

2021-02-01 23:43 UTC, dialpad-drew commented
> 1. Yes, I was, I thought that the icons did show up in the local host.

I don't see them. I _think_ you have to add the icons to the specific icon JSON file to get them to render. In this case, I think it's `dialtone/docs/_data/svg-brand.json` that you'll want to look at.

> 2. I'll rename the icons to match the current standard.
💯 

> 3. I made sure to update the branch when I started staging, but now that you mentioned it, I am not too sure how to check if my branch is the most up-to-date or not
I'll DM you.

2021-02-05 18:37 UTC, dialpad-drew commented
Vicky and I spoke and we're gonna try this again on a new branch.

2021-02-05 18:37 UTC, closed without merging