DT-31 Modal transition: Refactor to use Vue transition compatible CSS classes
dialpad/dialtone-legacy pull request #407
Opened 2021-08-20 14:21 UTC by josedialpad

## Description
Issue: https://switchcomm.atlassian.net/browse/DT-31
This PR adds modal transition classes to apply during transition instead of relying on `aria-hidden` prop to transition.

Updated documentation modal examples in order to use these classes.

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [ ] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Update, remove, or extend all affected documentation.
 - [x] Provide a description what is being changed, extended, or removed.
 - [x] Link to any issue(s) this request is resolving.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
 - [x] Request a review from Drew Chandler, Joshua Hynes, or Ted Goas.

## Obligatory GIF
![CleanShot 2021-08-20 at 10 59 51](https://user-images.githubusercontent.com/83774467/130245005-b74f4970-7ee7-41ee-b1cd-427c1262e09a.gif)

2021-08-20 22:20 UTC, dialpad-drew commented
How does this impact the DT6 implementation? Would we need to add these new classes to the class table?

2021-08-23 17:26 UTC, josedialpad commented
@dialpad-drew since with this PR the transition is made with CSS classes, in the DT6 implementation we need to apply the classes during the transition. In the [following PR](https://github.com/dialpad/dialtone-vue/pull/137) the Vue transition wrapper was used with these new transition classes.

> Would we need to add these new classes to the class table?

Yes, and we could add some documentation about it in the dialtone documentation.

2021-08-24 17:56 UTC, dialpad-drew approved these changes

2021-08-25 17:40 UTC, dialpad-drew commented
Are we waiting for David's approval?

2021-08-25 18:00 UTC, josedialpad commented
@dialpad-drew ideally yes. I'd like his review especially in the implementation PR https://github.com/dialpad/dialtone-vue/pull/137 but If we're good with these changes we can merge this and just wait for the review on the implementation PR (probably after Dialtone 6 migration since it's the priority).

2021-08-26 00:34 UTC, dbecherdialpad requested changes

2021-08-26 00:34 UTC, dbecherdialpad commented on lib/build/less/components/modal.less
>      @media (prefers-reduced-motion) {
I think this `prefers-reduced-motion` query needs to be wrapped around the new transition classes below (and make sure the classes work with `prefers-reduced-motion` enabled)

2021-08-26 18:48 UTC, josedialpad commented on lib/build/less/components/modal.less
>      @media (prefers-reduced-motion) {
Thanks, you're right. Updated to put `prefers-reduced-motion` in the transition classes. https://github.com/dialpad/dialtone/pull/407/commits/17ff5c43ac3dcc33de9998f30820e0bd4d7525b1

> and make sure the classes work with prefers-reduced-motion enabled

The classes work but not the transition as expected.

2021-09-29 17:29 UTC, dbecherdialpad approved these changes

2021-11-05 18:43 UTC, merged