Updated font, border and background colors of disabled styles
dialpad/dialtone-legacy pull request #470
Opened 2021-10-06 19:34 UTC by juliodialpad

## Description
The problem is we often disable inputs while data is saving data to the server, so this new disabled style is more jarring now.

https://switchcomm.atlassian.net/browse/DT-168

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
 - [x] Request a review from Brad Paugh, David Becher, or Drew Chandler.

## Obligatory GIF (super important!)
![](https://media.giphy.com/media/26n6xF5M2Ht4eKdO0/giphy.gif)

2021-10-06 22:48 UTC, dialpad-drew commented
Something I didn't catch in the design: can we make these arrows on the right the same color as the text?

<img width="772" alt="Screen Shot 2021-10-06 at 4 46 06 PM" src="https://user-images.githubusercontent.com/77751297/136293901-7956de7e-32f6-4b6b-bf0c-d09142f94e1c.png">

2021-10-07 19:35 UTC, juliodialpad commented
In order to get that done, I'll need to add a class to dialtone **d-select--disabled**, it's ok if I do it this way? 

It's hard to style the arrow based on disabled state because the disabled state is on a children of d-select and the :before and :after that represent the arrows are siblings of .d-select__input.

![image](https://user-images.githubusercontent.com/87546543/136450783-a2832d87-3ad1-48a9-8055-d5fe5fedc31e.png)

2021-10-07 20:15 UTC, dialpad-drew commented
Hmmm, [CSS Tricks](https://css-tricks.com/almanac/selectors/d/disabled/) says you can chain these, though I haven't been able to get it to work.

> :disabled can be “chained” with other pseudo-selectors: like :before or :after to generate icons or text to provide more user feedback.

2021-10-08 15:51 UTC, juliodialpad commented
> Hmmm, [CSS Tricks](https://css-tricks.com/almanac/selectors/d/disabled/) says you can chain these, though I haven't been able to get it to work.
> 
> > :disabled can be “chained” with other pseudo-selectors: like :before or :after to generate icons or text to provide more user feedback.

The real problem here is that you cannot style a parent element based on child status, I've been investigating and seems the only way to do that is javascript, or adding a class like I did

2021-10-11 15:49 UTC, dialpad-drew commented
I'm ok w/ this. I'd like to hold off and get @braddialpad 's 👍  or 👎 before merging. Also, we'll need to update the Vue component as well with this new class, so I'll make a story for that.

2021-10-11 15:50 UTC, dialpad-drew commented
> > Hmmm, [CSS Tricks](https://css-tricks.com/almanac/selectors/d/disabled/) says you can chain these, though I haven't been able to get it to work.
> > > :disabled can be “chained” with other pseudo-selectors: like :before or :after to generate icons or text to provide more user feedback.
> 
> The real problem here is that you cannot style a parent element based on child status, I've been investigating and seems the only way to do that is javascript, or adding a class like I did

BTW, is the class you added pushed up? I don't see the style update in the deploy preview.

2021-10-11 15:52 UTC, juliodialpad commented
> > > Hmmm, [CSS Tricks](https://css-tricks.com/almanac/selectors/d/disabled/) says you can chain these, though I haven't been able to get it to work.
> > > > :disabled can be “chained” with other pseudo-selectors: like :before or :after to generate icons or text to provide more user feedback.
> > 
> > 
> > The real problem here is that you cannot style a parent element based on child status, I've been investigating and seems the only way to do that is javascript, or adding a class like I did
> 
> BTW, is the class you added pushed up? I don't see the style update in the deploy preview.

I was waiting for comments to push it, I'll push it so you can see it.

2021-10-11 20:59 UTC, dialpad-drew approved these changes
LGTM, but want to wait for Brad.

2021-10-12 16:16 UTC, braddialpad commented
> In order to get that done, I'll need to add a class to dialtone **d-select--disabled**, it's ok if I do it this way? 
 

yep this is fine IMO

2021-10-12 16:17 UTC, braddialpad requested changes

2021-10-12 16:17 UTC, braddialpad commented on docs/components/select.html
> +  <div class="d-select d-select--disabled>
Missed a quote here.

2021-10-12 16:30 UTC, juliodialpad commented on docs/components/select.html
> +  <div class="d-select d-select--disabled>
Fixed, thanks

2021-10-12 16:31 UTC, braddialpad approved these changes

2021-10-12 16:31 UTC, merged