feat: add responsive variations
dialpad/dialtone-legacy pull request #474
Opened 2021-10-15 20:32 UTC by juliodialpad

## Description
We need a [way to create responsive variations](https://switchcomm.atlassian.net/browse/DT-184) for all the utility classes in Dialtone.

Found a [postcss plugin](https://github.com/derek-duncan/postcss-responsify) that could be used but needed some fixes in order to adapt it to our project so we decided to include the customized plugin in our codebase.

Also needed to remove a lot of imports that were causing a lot of issues and causing the build times to be slower.

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
 - [x] Request a review from Brad Paugh, David Becher, or Drew Chandler.

## Obligatory GIF (super important!)
![](https://media.giphy.com/media/iJJ6E58EttmFqgLo96/giphy.gif)

2021-10-18 19:26 UTC, braddialpad requested changes
Some deletions here I'm not really understanding. Maybe you can explain?

2021-10-18 19:26 UTC, braddialpad commented on docs/assets/less/dialtone-docs.less
> +@import "../../../lib/build/less/variables/spacing";
Can these be (reference)?

2021-10-18 19:26 UTC, braddialpad commented on lib/build/less/components/button.less
> +//@import (reference) "../variables/icons.less";
Do we still need to comment all these and other imports? If it is not breaking anything we should probably just keep them for better future flexibility in compiling our less

2021-10-18 19:26 UTC, braddialpad commented on lib/build/less/utilities/colors.less
> -
Don't think we can just delete all this?

2021-10-18 19:26 UTC, braddialpad commented on lib/build/less/utilities/backgrounds.less
> -
Don't think we can just delete all this?

2021-10-18 19:26 UTC, braddialpad commented on lib/build/less/utilities/flex.less
> -@flex-columns: 12;
don't we still need this?

2021-10-18 19:34 UTC, juliodialpad commented on docs/assets/less/dialtone-docs.less
> +@import "../../../lib/build/less/variables/spacing";
No, if you put those as a (reference) the site doesn't work well, those variables don't exist

2021-10-18 19:39 UTC, juliodialpad commented on lib/build/less/components/button.less
> +//@import (reference) "../variables/icons.less";
Yeah, if they're not commented, the code duplicates due to the (multiple) imports in dialtone.less

```less
// Create a copy of the classes to make them responsive
@responsive {
  @import (multiple) "utilities/backgrounds";
  @import (multiple) "utilities/borders";
  @import (multiple) "utilities/colors";
  @import (multiple) "utilities/effects";
  @import (multiple) "utilities/flex";
  @import (multiple) "utilities/grid";
  @import (multiple) "utilities/interactivity";
  @import (multiple) "utilities/layout";
  @import (multiple) "utilities/sizing";
  @import (multiple) "utilities/spacing";
  @import (multiple) "utilities/svg";
  @import (multiple) "utilities/typography";
}
```

and if we don't import it as (multiple) the classes don't get generated

2021-10-18 19:46 UTC, juliodialpad commented on lib/build/less/utilities/backgrounds.less
> -
I moved this code to utilities/internals.less

2021-10-18 19:48 UTC, juliodialpad commented on lib/build/less/utilities/colors.less
> -
Moved to utilities/internals.less

2021-10-18 19:50 UTC, juliodialpad commented on lib/build/less/utilities/flex.less
> -@flex-columns: 12;
moved to utilities/internals.less

2021-10-18 19:56 UTC, juliodialpad commented on lib/build/less/utilities/grid.less
> -
Moved this to variables/layout.less

2021-10-18 19:57 UTC, juliodialpad commented on lib/build/less/utilities/flex.less
> -@flex-columns: 12;
And the line 103, was moved to variables/layout.less

2021-10-18 19:58 UTC, juliodialpad commented on docs/_includes/header.html
> +    <nav role="navigation" class="lg:d-d-none d-ml64 d-flow8">
This shouldn't be here, I'll remove it

2021-10-18 19:59 UTC, juliodialpad commented on docs/_includes/header.html
> +        <div class="lg:d-d-none d-d-flex d-flow4">
Neither this should be here, I'll remove it

2021-10-18 20:05 UTC, braddialpad commented on lib/build/less/components/button.less
> +//@import (reference) "../variables/icons.less";
Ah I see, yep let's just leave it then

2021-10-18 20:06 UTC, braddialpad commented on docs/assets/less/dialtone-docs.less
> +@import "../../../lib/build/less/variables/spacing";
Right, this must be because we aren't building from a "master" file like how we build the css.

2021-10-18 20:08 UTC, braddialpad commented on lib/build/less/utilities/flex.less
> -@flex-columns: 12;
Ah I see, yeah the internals.less wasn't expanded due to large diff so I missed it

2021-10-18 20:13 UTC, juliodialpad commented on docs/assets/less/dialtone-docs.less
> +@import "../../../lib/build/less/variables/spacing";
Reverted those changes, I added (reference) to the dialtone-variables.less file and that was wrong, fixed and tested that this lines should be (reference)

2021-10-18 20:23 UTC, braddialpad commented on docs/assets/less/dialtone-docs.less
> +@import "../../../lib/build/less/variables/spacing";
nice

2021-10-18 20:50 UTC, braddialpad approved these changes
Thanks! Remember not to merge this until we have a solution implemented for https://switchcomm.atlassian.net/browse/DT-174

2021-11-30 22:17 UTC, braddialpad approved these changes

2021-12-01 00:23 UTC, merged