Dt 305 add muted button styles
dialpad/dialtone-legacy pull request #516
Opened 2021-12-04 22:44 UTC by juliodialpad

## Description

Add muted and muted outline button styles to Dialtone. The styles already existed on Dialtone so just updated the variables and added the examples.

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
 - [x] Request a review from Brad Paugh, David Becher, or Drew Chandler.

## Obligatory GIF (super important!)
![](https://media.giphy.com/media/VKf2GfUCYKq5GJ1VRs/giphy.gif)

2021-12-06 20:04 UTC, braddialpad approved these changes

2021-12-07 00:16 UTC, dialpad-drew commented
Idea for missing copy: 
> The muted button style is used to communicate non-primary actions for contexts in which the base style may not work (e.g. colored backgrounds, validation components, etc). This style’s use should be rare. When in doubt, use the [base button style](”The muted button style is used to communicate non-primary actions for contexts in which the base style may not work (e.g. colored backgrounds, validation components, etc). This style’s use should be rare. When in doubt, use the base button style.”).

Can we make sure to add muted button as one of the ~three~ four styles. That would also include moving that example up so its in the right order (see table of contents below).

<img width="1135" alt="Screen Shot 2021-12-06 at 4 56 39 PM" src="https://user-images.githubusercontent.com/77751297/144941569-02704f7c-f9a3-4939-bb63-ab55a6c9f435.png">

Also, I know it's scope creep, but it's small and we're already in the file. Can we remove the "cursor styles" section, update the "disabled" section's `.d-btn--disabled` example to show what was in "cursor styles" example, and update the "disabled" section's first paragraph's last sentence to read this:

> Using the class also requires `aria-disabled` and a wrapper to disable pointer events.

<img width="810" alt="Screen Shot 2021-12-06 at 5 01 29 PM" src="https://user-images.githubusercontent.com/77751297/144942965-6f5ec691-5871-45a4-b02c-43fa6d12c9cf.png">

@braddialpad is the sentence about the pointer events accurate? Or should we say pointer events and the click event both need to be disabled?

2021-12-07 02:05 UTC, braddialpad commented
> @braddialpad is the sentence about the pointer events accurate? Or should we say pointer events and the click event both need to be disabled?

The wrapper does not actually do anything with pointer events, it only displays a "not allowed" symbol on mouse over. d-btn--disabled is what sets pointer-events to none. We should probably still mention the click event

2021-12-07 19:32 UTC, braddialpad commented on docs/components/button.html
> +      {% paragraph %}The muted button style is used to communicate...{% endparagraph %}
We still need to update the copy here with what drew posted.

2021-12-08 00:01 UTC, juliodialpad commented on docs/components/button.html
> +      {% paragraph %}The muted button style is used to communicate...{% endparagraph %}
Oops missed that one, thought I've updated it, should be fixed now.

2021-12-08 16:44 UTC, braddialpad requested changes

2021-12-08 16:44 UTC, braddialpad commented on docs/components/button.html
> +      {% paragraph %}Buttons can be disabled using either the {% code %}disabled{% endcode %} attribute or a Dialtone class. Use the attribute when a button should appear disabled and not recieve foc
Let's change the last sentence to: Using the class also requires aria-disabled and a wrapper to display the "not allowed" pointer. Additional javascript implementation is required to prevent the click event.

2021-12-08 17:43 UTC, braddialpad approved these changes

2021-12-08 17:46 UTC, merged