feat: add documentation for new skeleton component
dialpad/dialtone-legacy pull request #521
Opened 2021-12-17 13:14 UTC by nikitadialpad

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
 - [x] Request a review from Brad Paugh, David Becher, or Drew Chandler.

## Obligatory GIF (super important!)

![snA2OVsg9sMRW](https://user-images.githubusercontent.com/81983630/146549862-713f338e-5510-4541-bd82-6e5ebd6fc7be.gif)

2021-12-17 13:15 UTC, nikitadialpad commented on docs/assets/less/dialtone-docs.less
> +.skeleton-placeholder {
@braddialpad hey Brad, what do you think may be we can add this class to dialtone and re-use it after in dialtone-vue?

2022-01-04 19:25 UTC, braddialpad commented on docs/assets/less/dialtone-docs.less
> +.skeleton-placeholder {
I agree, best to have the css in dialtone if we can.

2022-01-04 19:37 UTC, braddialpad requested changes
Couple small grammatical things. Maybe an additional example as well?

2022-01-04 19:37 UTC, braddialpad commented on docs/components/skeleton.html
> +        Skeleton loader are grey animated shapes that visually mimics the content.
pluralization issue:
Skeleton loaders are grey animated shapes that visually mimic the content

2022-01-04 19:37 UTC, braddialpad commented on docs/components/skeleton.html
> +        For text, use height that matches multiple of {% code %}8px{% endcode %}.
"multiples"

2022-01-04 19:37 UTC, braddialpad commented on docs/components/skeleton.html
> +      {% endcodeWell %}
Can we also show a circle example?

2022-01-04 20:05 UTC, dialpad-drew commented
May not be a bad idea to re-visit the [story as written](https://switchcomm.atlassian.net/jira/software/projects/DT/boards/187?selectedIssue=DT-237). I believe the intent was to show basic example(s) and really push developers to the Vue component and its documentation as this shouldn't be implemented in CSS only.

2022-01-05 10:33 UTC, nikitadialpad commented on docs/components/skeleton.html
> +        Skeleton loader are grey animated shapes that visually mimics the content.
tnx, fixed, will update dialtone-vue doc as well

2022-01-05 10:34 UTC, nikitadialpad commented on docs/components/skeleton.html
> +        For text, use height that matches multiple of {% code %}8px{% endcode %}.
tnx, fixed, will update dialtone-vue documentation as well

2022-01-05 11:19 UTC, nikitadialpad commented on lib/build/less/utilities/layout.less
> -//@import (reference) '../variables/spacing.less';
cleaned up some commented imports

2022-01-05 11:23 UTC, nikitadialpad commented on lib/build/less/utilities/grid.less
> +);
I saw that issue with `lesshint` and utilities folder: `lesshint` formatting was incorrect in some places because of less syntax specific declarations, even `lesshint` does the formatting incorrectly.
In case this issue will be faced again, I would propose to add this file to lesshint excludedFiles

2022-01-05 11:55 UTC, nikitadialpad commented on docs/assets/less/dialtone-docs.less
> +.skeleton-placeholder {
moved skeleton styles to independent component ([db73](https://github.com/dialpad/dialtone/pull/521/commits/146ab9d47b2ea8d5bce966dafc4d538c203bdb73))

2022-01-05 17:28 UTC, braddialpad commented on docs/components/skeleton.html
> +      {% endcodeWell %}
not necessary after drews comment

2022-01-05 17:29 UTC, braddialpad commented on lib/build/less/utilities/grid.less
> +);
sounds good

2022-01-05 20:55 UTC, braddialpad commented
Let's simplify this page and change the language to reference the vue storybook page as drew has mentioned.

2022-01-06 09:25 UTC, nikitadialpad commented on lib/build/less/utilities/layout.less
> -//@import (reference) '../variables/spacing.less';
@juliodialpad as we discussed reverted corresponding commented import changes

2022-01-06 09:26 UTC, nikitadialpad commented
> Let's simplify this page and change the language to reference the vue storybook page as drew has mentioned.

as we discussed removed skeleton examples

2022-01-06 21:29 UTC, dialpad-drew commented
Sorry, I think there's a miscommunication. I'm trying to understand how we got "remove examples" from this story:

> *Create a Skeleton page on dialpad.design
*Provide awareness on dialpad.design that this component is offered as Vue only
*Provide just the basic definition of Skeleton, basic examples (without code snippets) and then create crosslinks to Storybook

When we groomed this, I thought we'd talked about adding basic examples, no code snippets, and adding language that this is a Vue-only component with an additional CTA pushing people to Storybook. What am I missing?

2022-01-11 10:55 UTC, nikitadialpad commented
@dialpad-drew 
hey Drew, sorry for misunderstanding, I meant removed code snippets as story says `without code snippets` to force using `dialtone-vue` doc.

2022-01-11 17:02 UTC, braddialpad commented
> @dialpad-drew hey Drew, sorry for misunderstanding, I meant removed code snippets as story says `without code snippets` to force using `dialtone-vue` doc.
> 
> #update 1 : seems I got your idea :) reverted the last example but without code snippet
> 
> ![Screenshot 2022-01-11 at 13 01 20](https://user-images.githubusercontent.com/81983630/148930969-5d920f61-9320-432d-b025-3d785e5251e6.png) how it looks like now. am I right you were about that?

We should probably remove a lot of the detail from this page since it's supposed to just be directing to storybook.

We can keep the header definition. Below it we can put something like:

The Skeleton component only exists in Dialtone Vue. Please follow this link for more details on it's usage:

[Dialtone Vue Skeleton](https://vue.dialpad.design/?path=/story/components-skeleton--default)

We can probably remove the dos and donts sections

2022-01-11 19:06 UTC, braddialpad approved these changes
Looks good now, thanks!

2022-01-12 02:54 UTC, dbecherdialpad approved these changes

2022-01-12 02:54 UTC, dbecherdialpad commented on docs/components/skeleton.html
> +        more details on it's usage.
*its

2022-01-12 08:37 UTC, nikitadialpad commented on docs/components/skeleton.html
> +        more details on it's usage.
fixed, tnx

2022-01-13 01:00 UTC, dialpad-drew approved these changes

2022-01-13 11:43 UTC, merged