feat: add toggle styles
dialpad/dialtone-legacy pull request #533
Opened 2022-01-20 20:18 UTC by modialpad

## Description

Adds the new Dialtone Toggle `d-toggle` styles. See [Figma](https://www.figma.com/file/nAvI4GmMxuzdRmZ2HdUbgs/Toggle-Proposal?node-id=309%3A33).

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
 - [x] Request a review from Brad Paugh, David Becher, or Drew Chandler.

## Obligatory GIF (super important!)
![image](https://user-images.githubusercontent.com/88498639/150413659-139e0704-9652-40ba-9672-80cc792da33d.png)
![DtToggle Styles Gif](https://user-images.githubusercontent.com/88498639/150415363-bd4e757a-f3de-4b80-ba6e-f26213b708b9.gif)

2022-01-20 20:36 UTC, tedgoas-dialpad reviewed
One question about the stacked pattern. Component itself looks good!

2022-01-20 20:36 UTC, tedgoas-dialpad commented on docs/components/toggle.html
> +      <li>If you have a group of related toggles, use a {% code %}fieldset{% endcode %} to group them and a {% code %}legend{% endcode %} to title the group. For further information, please visit Gov
Does this link need a class on it? I'd expect it to be purple, but it's showing as blue. Is this an issue with the docs site? cc @braddialpad 

<img width="743" alt="Screen Shot 2022-01-20 at 3 30 58 PM" src="https://user-images.githubusercontent.com/65190890/150417429-01049ef1-22df-4500-9ac3-36ad3b36951b.png">

2022-01-20 20:36 UTC, tedgoas-dialpad commented on docs/components/toggle.html
> +      {% header "h3", "Stacked Group" %}
This is an interesting variant on this. I wonder if we could expand this stacked pattern to left-align the labels and right-align the toggle , like so:

![image](https://user-images.githubusercontent.com/65190890/150417972-d2c8e74b-2009-4ce0-81b7-2b21fcd01bd6.png)


(instead of having the label and toggle squished together)

2022-01-20 21:11 UTC, braddialpad commented on docs/components/toggle.html
> +      {% header "h3", "Stacked Group" %}
hmmm wondering if we might just want this to be the default for everything. @modialpad should be a simple change, would just need to add `d-jc-space-between` to the divs with class `d-toggle-group`

2022-01-20 21:14 UTC, braddialpad commented on docs/components/toggle.html
> +      <li>If you have a group of related toggles, use a {% code %}fieldset{% endcode %} to group them and a {% code %}legend{% endcode %} to title the group. For further information, please visit Gov
yep it just need `class="d-link"` added to it

2022-01-20 21:14 UTC, tedgoas-dialpad commented on docs/components/toggle.html
> +      {% header "h3", "Stacked Group" %}
Ooh that's a clever way to handle it, good suggestion Brad!

2022-01-20 21:28 UTC, modialpad commented on docs/components/toggle.html
> +      {% header "h3", "Stacked Group" %}
I updated the styles to look something like this:

2022-01-20 21:29 UTC, modialpad commented on docs/components/toggle.html
> +      {% header "h3", "Stacked Group" %}
@tedgoas-dialpad @braddialpad Would this work?

2022-01-20 21:29 UTC, modialpad commented on docs/components/toggle.html
> +      <li>If you have a group of related toggles, use a {% code %}fieldset{% endcode %} to group them and a {% code %}legend{% endcode %} to title the group. For further information, please visit Gov
Done

2022-01-20 21:49 UTC, braddialpad requested changes
Looks pretty good! My comments are mostly related to getting rid of fixed px values.

2022-01-20 21:49 UTC, braddialpad commented on lib/build/less/components/toggle.less
> +.d-toggle {
We generally try to avoid using px values as they are not scalable. Try to use the built in dialtone stops for the specific property if available, if not you can possibly use our [spacing units](https://github.com/dialpad/dialtone/blob/staging/lib/build/less/variables/spacing.less). I will show you examples of some fixes below and let you fix the rest. 

If you look into some of the other less components in the system you'll probably see where I'm coming from.

2022-01-20 21:49 UTC, braddialpad commented on lib/build/less/components/toggle.less
> +  line-height: 20px;
`line-height: var(--lh4);`

2022-01-20 21:49 UTC, braddialpad commented on lib/build/less/components/toggle.less
> +  width: 48px;
`width: var(--su48)`

2022-01-20 21:49 UTC, braddialpad commented on lib/build/less/components/toggle.less
> +  border-radius: 25px;
the dialtone stop is `var(--br24)`. 1 pixel difference, guessing it's close enough to work but try it out.

2022-01-20 21:49 UTC, braddialpad commented on lib/build/less/components/toggle.less
> +    width: 20px;
20px is not a dialtone stop, but you can do `calc(var(--su16) + var(--su4))`

2022-01-20 21:49 UTC, braddialpad commented on lib/build/less/components/toggle.less
> +    border-radius: 50%;
`border-radius: var(--br-circle)`

2022-01-20 21:49 UTC, braddialpad commented on docs/components/toggle.html
> +      <li>If you have a group of related toggles, use a {% code %}fieldset{% endcode %} to group them and a {% code %}legend{% endcode %} to title the group. For further information, please visit Gov
probably don't need quotes around "Using the fieldset and legend elements" since it's a link

2022-01-20 21:49 UTC, braddialpad commented on lib/build/less/components/toggle.less
> +  cursor: no-drop;
Is there a reason we use `no-drop` instead of `not-allowed`?

2022-01-20 21:49 UTC, braddialpad commented on docs/components/toggle.html
> +      <li>If you have a group of related toggles, use a {% code %}fieldset{% endcode %} to group them and a {% code %}legend{% endcode %} to title the group. For further information, please visit Gov
add `class="d-link"` as Ted mentioned.

2022-01-20 22:44 UTC, braddialpad commented on docs/components/toggle.html
> +      {% header "h3", "Stacked Group" %}
I think that's fine for the example on this doc site. Keep in mind for the vue component we may not want to have this on by default so the user can pass in whatever justify content class they need.

2022-01-21 15:38 UTC, modialpad commented on lib/build/less/components/toggle.less
> +.d-toggle {
I see, I updated the file with our `--su` vars

2022-01-21 15:38 UTC, modialpad commented on lib/build/less/components/toggle.less
> +  line-height: 20px;
Done

2022-01-21 15:38 UTC, modialpad commented on lib/build/less/components/toggle.less
> +  width: 48px;
Done

2022-01-21 15:40 UTC, modialpad commented on lib/build/less/components/toggle.less
> +  border-radius: 25px;
I updated this to a --su48 as it was closer to what the Figma designs expected

2022-01-21 15:40 UTC, modialpad commented on lib/build/less/components/toggle.less
> +    width: 20px;
Done

2022-01-21 15:40 UTC, modialpad commented on lib/build/less/components/toggle.less
> +    border-radius: 50%;
Done

2022-01-21 15:40 UTC, modialpad commented on docs/components/toggle.html
> +      <li>If you have a group of related toggles, use a {% code %}fieldset{% endcode %} to group them and a {% code %}legend{% endcode %} to title the group. For further information, please visit Gov
Added

2022-01-21 15:42 UTC, modialpad commented on lib/build/less/components/toggle.less
> +  cursor: no-drop;
Seems like `not-allowed` has the same cursor, and is better semantically since `no-drop` refers to draggable elements

2022-01-21 15:44 UTC, modialpad commented on lib/build/less/components/toggle.less
> +    width: 20px;
I made a fair bit of `calc` usage inside that file. I know it's widely supported by most browsers by now, but do we see an issue using `calc` in older or incompatible environments?

2022-01-21 19:27 UTC, braddialpad commented on lib/build/less/components/toggle.less
> +    width: 20px;
It has very good modern browser support, not something we need to worry about:
https://caniuse.com/calc

2022-01-21 19:28 UTC, braddialpad approved these changes
awesome thank you! I will do a release once you merge this

2022-01-21 19:41 UTC, merged