docs: fix anchor scroll position
dialpad/dialtone-legacy pull request #623
Opened 2022-06-30 19:40 UTC by JonathanPaugh

## Description
Add an offset when the window scrolls to an anchor position to compensate for sticky header size.

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

## Obligatory GIF (super important!)
![](https://c.tenor.com/cv-mmIK-inMAAAAd/i-could-just-sit-there-and-scroll-and-scroll-and-scroll.gif)

2022-06-30 19:53 UTC, JonathanPaugh commented on docs/.vuepress/client.js
> +    }
VuePress creates the router and then [provides the instance](https://v2.vuepress.vuejs.org/advanced/cookbook/usage-of-client-config.html#enhance) so we don't have access to set the [scrollBehavior](https://router.vuejs.org/api/#scrollbehavior) with `createRouter` as intended. Instead it seems the best solution is to wrap the function provided on the router instance and modify the offset if it is an anchor.

2022-06-30 20:00 UTC, JonathanPaugh commented on docs/.vuepress/theme/layouts/Layout.vue
> +    );
`globalProperties` may not be the best way to share this value. [Provide / Inject](https://vuejs.org/guide/components/provide-inject.html#provide) seemed like a promising solution, however only `Provide(...)` can be used at both the app and component level but `Inject(...)` can only be used at the component level and it is needed at the app level.

2022-06-30 20:53 UTC, josedialpad commented
![2022-06-30 at 17 47 52@2x](https://user-images.githubusercontent.com/83774467/176775682-03299af5-4ee6-4c51-b3cb-0ebaecbc2481.png)

Is it possible to apply this fix to the header anchor? Seems that's the same issue with the TOC links

2022-06-30 20:58 UTC, JonathanPaugh commented
> ![2022-06-30 at 17 47 52@2x](https://user-images.githubusercontent.com/83774467/176775682-03299af5-4ee6-4c51-b3cb-0ebaecbc2481.png)
> 
> Is it possible to apply this fix to the header anchor? Seems that's the same issue with the TOC links

Hmm I didn't notice that, I'll look into it.

2022-06-30 21:17 UTC, braddialpad requested changes
While this works for the most part, it's a lot of weird overrides and pretty hard to understand. I think it might be possible to implement a pure css solution using [scroll-margin-top](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-top) `scroll-margin-top: [OFFSET]px;`. This would have to be generated to be on each heading, but I locally edited the CSS and it seemed to work.

Let's at least try this, if it doesn't work for some reason we can go back to the method in this PR.

2022-06-30 21:22 UTC, josedialpad commented on docs/.vuepress/theme/layouts/Layout.vue
> +    );
Another approach that could be simpler, is to use the `--navbar-height` custom property that vuepress has. Actually, I checked in the [Vuepress docs](https://v2.vuepress.vuejs.org/guide/#why-not) and seems that using a combination of 
```
margin-top: calc(0.5rem - var(--navbar-height));
padding-top: calc(1rem + var(--navbar-height));
```
does the trick for all the links.

2022-06-30 23:38 UTC, JonathanPaugh commented on docs/.vuepress/theme/layouts/Layout.vue
> +    );
It seems we do have this styling:

<img width="562" alt="image" src="https://user-images.githubusercontent.com/33143001/176795163-6fa2a1ce-a582-4c27-b0b4-05b638a7832f.png">

It gets overridden by a bunch of other stylings:

<img width="560" alt="image" src="https://user-images.githubusercontent.com/33143001/176794967-f6ec7710-bd8d-4524-8199-89894b181dab.png">

If I manually force it to take on the margin and padding it seems to work well.

I found the main style that is overriding it in `docs/assets/css/dialtone-docs.css` which seems to be an auto generated file, I'm not sure where it comes from.

The other style overriding is from `docs/.vuepress/styles/palette.scss` which I can just remove, so it's not a problem.

2022-07-01 00:13 UTC, JonathanPaugh commented on docs/.vuepress/theme/layouts/Layout.vue
> +  });
It now modifies the css variable for `navbar-height` instead.

2022-07-01 00:15 UTC, JonathanPaugh commented on docs/assets/less/overrides.less
> +    padding-top: calc(1rem + var(--navbar-height));
Reverted all the other code, this is all that was needed. 🙂

2022-07-01 00:24 UTC, braddialpad approved these changes
Muuuuuuch nicer!

2022-07-01 15:52 UTC, josedialpad approved these changes
w/ a comment

2022-07-01 15:52 UTC, josedialpad commented on docs/.vuepress/theme/layouts/Layout.vue
> +  });
Just add the `immeadiate` option to the watcher so it sets the correct value from the first run

2022-07-04 16:03 UTC, merged