WIP: Add Presence
dialpad/dialtone-legacy pull request #716
Opened 2022-10-21 20:47 UTC by modialpad

## Description
Provide a description of what this pull request is adding, updating, extending, or removing. If this request is addressing an issue, please link to that issue.

## Pull Request Checklist

 - [ ] Ask the contributors if a similar effort is already in process or has been solved.
 - [ ] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [ ] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [ ] Ensure all `gulp` scripts successfully compile.
 - [ ] Update, remove, or extend all affected documentation.
 - [ ] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

## Obligatory GIF (super important!)
![](path/to/gif)

2022-10-24 20:39 UTC, braddialpad requested changes
Thanks for this Mo!

2022-10-24 20:39 UTC, braddialpad commented on docs/components/presence.md
> +The best accessibility is semantic HTML. Most screen readers understand how to parse buttons if they’re correctly formatted.
> Most screen readers understand how to parse buttons if they’re correctly formatted.

Is this relevant to this component since it's not a button?

Since the component is just a visual indicator do we need to provide instruction to the developer using it on how it should be read out via screen reader? (aria-label if interactive, maybe sr-only class if not)

2022-10-24 20:39 UTC, braddialpad commented on lib/build/less/components/presence.less
> +  border-radius: 50% !important;
hmm why `!important`? We only usually set this on utility classes that are meant to be immutable.

2022-10-24 20:39 UTC, braddialpad commented on docs/components/presence.md
> +### Best practices
Best practices is part of the `## Usage` section

2022-10-24 20:39 UTC, braddialpad commented on docs/components/presence.md
> +- A `presence` prop can be used to determine the status of the user, with the following valid statuses: `away`, `busy`, `active`, `offline`
"a css class can be set", remember as of right now dialtone knows nothing about vue.

2022-10-24 20:39 UTC, braddialpad commented on docs/components/presence.md
> +- A Presence component should be used as a way to show the current status of a user.
Is this all it should be used for? Could this component be used to show status for something that is not a user?

2022-10-24 20:39 UTC, braddialpad commented on lib/build/less/components/presence.less
> +.d-presence {
Is there a figma for this?

2022-10-25 14:10 UTC, modialpad commented on lib/build/less/components/presence.less
> +.d-presence {
I don't think there is an independent Figma just for this. I got the general idea of this design from the [Leftbar Figma](https://www.figma.com/file/6n4RCYk2y2rYx5c4hL088f/DP-2.0-Left-sidebar?node-id=1%3A13198) and then confirmed with @francisrupert through this [Jira ticket](https://dialpad.atlassian.net/browse/DT-745) the requirements of this component.

2022-10-25 14:13 UTC, modialpad commented on docs/components/presence.md
> +- A Presence component should be used as a way to show the current status of a user.
Good question, AFAIK the version of presence developed here this is meant to eventually be embedded as part of Avatar. I don't think it will be useful anywhere else but @francisrupert can confirm. It's possible that in the future we can extend the styles for presence for other use cases.

2022-10-25 14:49 UTC, modialpad commented on docs/components/presence.md
> +The best accessibility is semantic HTML. Most screen readers understand how to parse buttons if they’re correctly formatted.
Must have missed this while copying off of another template.

The only accessibility feature we'll need that this relevant to this is the announcement of any changes to the user's presence. It's not going to be interactive, so I think `sr-only` makes sense.

In the Vue component, I'm thinking we would add `role=status` [attribute](https://www.w3.org/WAI/WCAG22/Techniques/aria/ARIA22) and then append a `<span>` that has the sr-only text, like so:

```js
<div v-if="presence" class="d-presence" role="status">
 <span class="sr-only">{{ srText }} </span>
  <div
    class="d-presence__inner"
    :class="{
      'd-presence__inner--active': presence === 'active',
      'd-presence__inner--away': presence === 'away',
      'd-presence__inner--busy': presence === 'busy',
      'd-presence__inner--offline': presence === 'offline',
    }"
  />
</div>
```

2022-10-25 16:02 UTC, modialpad commented on lib/build/less/components/presence.less
> +  border-radius: 50% !important;
Removed

2022-10-25 16:02 UTC, modialpad commented on docs/components/presence.md
> +### Best practices
Done

2022-10-25 16:02 UTC, modialpad commented on docs/components/presence.md
> +- A `presence` prop can be used to determine the status of the user, with the following valid statuses: `away`, `busy`, `active`, `offline`
Re-wrote this to mention CSS classes

2022-10-25 16:59 UTC, braddialpad commented on docs/components/presence.md
> +The best accessibility is semantic HTML. Most screen readers understand how to parse buttons if they’re correctly formatted.
Sounds good. Might want to have a way to make this optional since the developer might not always want presence to be aria-live announced. Suppose it could just be if the srText was falsey.

2022-10-25 17:01 UTC, braddialpad commented on docs/components/presence.md
> +- A Presence component should be used as a way to show the current status of a user.
Since this is such a standalone indicator not really tied to anything I could see it used for other things in the future. This is fine for now though.

2022-10-25 17:05 UTC, braddialpad commented on docs/components/presence.md
> +The best accessibility is semantic HTML. Most screen readers understand how to parse buttons if they’re correctly formatted.
May want to just write in this section "You may wish to announce any live changes to this component via screen reader since this is only a visual indicator".

2022-10-25 17:17 UTC, braddialpad commented on lib/build/less/components/presence.less
> +.d-presence {
Thanks that's all I was looking for really.

Are you going to implement that "transparent border" around the presence indicator as part of the avatar?

2022-10-25 17:18 UTC, braddialpad approved these changes
I had a couple final comments but otherwise this is good to go.

2022-10-25 17:55 UTC, modialpad commented on lib/build/less/components/presence.less
> +.d-presence {
Isn't it already part of `d-presence` styles? `d-presence` creates the a greyish border and `d-presence__inner` will be the circle indicator itself.

For the Avatar work next, I'll basically be shoving a `<Presence/>` component inside Avatar and expose it through a prop. I don't have a Jira defined for this yet but I will create it soon.

2022-10-25 18:04 UTC, modialpad commented
@braddialpad when I commit locally, the `lint:code` command produces a few thousand errors:
![image](https://user-images.githubusercontent.com/88498639/197848305-f83afd22-a37e-47b1-b28c-854613b09e2f.png)

But on CI it's only a few warnings... I did notice a commit from @juliodialpad downgrading eslint, but I have version 8.22.0 and I still see this:

![image](https://user-images.githubusercontent.com/88498639/197848518-6772ddf8-3583-4139-befd-6fcc7ae0056a.png)

2022-10-25 18:12 UTC, juliodialpad commented
@modialpad what version of `node` are you using? I think we are using `node  v16.x` that might have to do with the error.

2022-10-25 18:35 UTC, modialpad commented
> @modialpad what version of `node` are you using? I think we are using `node v16.x` that might have to do with the error.

@juliodialpad I was using v16.14.0. I tested it out with CI's node version (v16.17.1 & npm 8.15.0) and I still see the same issue locally.

2022-10-25 18:48 UTC, juliodialpad commented
> > @modialpad what version of `node` are you using? I think we are using `node v16.x` that might have to do with the error.
> 
> @juliodialpad I was using v16.14.0. I tested it out with CI's node version (v16.17.1 & npm 8.15.0) and I still see the same issue locally.

I'm using v16.14.2, pulled your branch, did `npm install` and then `npm run lint:code`

<img width="832" alt="image" src="https://user-images.githubusercontent.com/87546543/197856622-dc144162-1b88-4625-bbe6-900b09457932.png">

And just having 2 warnings... did you removed `package-lock.json` or something?

2022-10-25 18:53 UTC, braddialpad commented
I'd try all the usual culprits, delete node_modules, delete package-lock, then npm install again

2022-10-25 20:10 UTC, modialpad commented
> I'm using v16.14.2, pulled your branch, did `npm install` and then `npm run lint:code`
> 
> <img alt="image" width="832" src="https://user-images.githubusercontent.com/87546543/197856622-dc144162-1b88-4625-bbe6-900b09457932.png">
> 
> And just having 2 warnings... did you removed `package-lock.json` or something?

Ok, may have found the cause. Apparently all the errors were happening under `docs/_site`. That's a generated folder, I had created it previously on the repo using the command `build:docsite`.  

The problem is that `eslintignore` did not include the folder `_site` as well, we only added it to .gitignore. So when I ran the lint command it also linted that whole folder.

I think the `_site` folder is not supposed to be available locally anyway but in any case `_site` should be definitely added to `eslintignore`.

2022-10-25 20:12 UTC, merged