feat(toggle): add small variant and indeterminate state
dialpad/dialtone-legacy pull request #725
Opened 2022-10-31 19:32 UTC by josedialpad

## Description
Jira ticket: https://dialpad.atlassian.net/browse/DT-737

Changes added by @francisrupert 🙌. I've just updated the examples in the docsite and created the PR to move forward with the vue implementation.

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

## Obligatory GIF (super important!)
![](https://i0.wp.com/codemyui.com/wp-content/uploads/2018/01/pizza-toggle-switch-in-css.gif?fit=880%2C440&ssl=1)
https://codemyui.com/pizza-toggle-switch-css/

2022-10-31 19:35 UTC, josedialpad commented on docs/components/toggle.md
> +  </button>
```suggestion
  <button id="Dialtone-Preview-Toggle3" class="d-toggle d-toggle--indeterminate d-mr8" aria-checked="mixed" type="button" role="checkbox">
    <span class="d-toggle__inner"></span>
  </button>
```

For the indeterminate state, shouldn't we use `role="checkbox` and `aria-checked="mixed"` since now has tri-state https://www.w3.org/WAI/ARIA/apg/example-index/checkbox/checkbox-mixed?

2022-10-31 20:07 UTC, braddialpad commented on docs/components/toggle.md
> +  </button>
Yep this is correct, the switch role does not support mixed/indeterminate.

2022-10-31 20:14 UTC, josedialpad commented on docs/components/toggle.md
> +  </button>
updated the indeterminate examples https://github.com/dialpad/dialtone/pull/725/commits/7e62bd6bbb5ad25df88b10ba4e82a5a551fae104

2022-10-31 20:23 UTC, braddialpad requested changes

2022-10-31 20:23 UTC, braddialpad commented on lib/build/less/components/toggle.less
> +  &--indeterminate {
needs to be added into the class list on the doc site.

2022-10-31 20:23 UTC, braddialpad commented on lib/build/less/components/toggle.less
> +  &--small {
Also needs to be in the class list

2022-10-31 20:23 UTC, braddialpad commented on docs/components/toggle.md
> +</div>
This whole section should probably be moved to other areas for consistency with other pages. The indeterminate styles can be added to the "base styles" section, and you could make a new section for "sizes"

2022-11-01 16:12 UTC, josedialpad commented on lib/build/less/components/toggle.less
> +  &--indeterminate {
Good catch, updated https://github.com/dialpad/dialtone/pull/725/commits/2e64829834a4df0356f6f23f7068b0cd1643b415

2022-11-01 16:12 UTC, josedialpad commented on lib/build/less/components/toggle.less
> +  &--small {
updated https://github.com/dialpad/dialtone/pull/725/commits/2e64829834a4df0356f6f23f7068b0cd1643b415

2022-11-01 16:13 UTC, josedialpad commented on docs/components/toggle.md
> +</div>
good call, updated in a separated section

2022-11-01 16:34 UTC, braddialpad approved these changes
Very nice, thanks!

2022-11-01 17:36 UTC, merged