refactor: usage of icons
dialpad/dialtone-legacy pull request #734
Opened 2022-11-10 18:42 UTC by juliodialpad

## Description

Refactored the usage of icons.
Updated migration guide with steps and tips to replace icons with new icon component.
Removed svg sizing documentation.

Created the list of potential icons to create/redraw [here](https://docs.google.com/spreadsheets/d/1ZyBhHEmG7xsbV9XHrpFiIOsSMNkPy9XnlsbqKYb8fWo/edit?usp=sharing)

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

## Obligatory GIF (super important!)
![](https://media.giphy.com/media/107QsHzZW54hJC/giphy.gif)

2022-11-10 18:58 UTC, braddialpad commented on migration_guide/MIGRATION_GUIDE.md
> +[Dialtone Vue - Icon component](https://vue.dialpad.design/?path=/story/components-icon--default)
There is still a ton of code in Dialpad that uses backbone and can't use vue components, so we'll need to provide the css/html way of doing it as well. Just make sure we emphasize to use the vue components in all vue code.

2022-11-10 18:58 UTC, braddialpad commented on migration_guide/MIGRATION_GUIDE.md
> +Do a search in [Icon docs](https://dialpad.design/components/icon.html) to find an icon that matches your needs.
Lets say to check with your designer or ask in #dialtone if you are having trouble finding a replacement for an existing icon.

2022-11-10 18:58 UTC, braddialpad commented on migration_guide/MIGRATION_GUIDE.md
> +Replace any custom usage of icon component with <dt-icon name="icon-name" size="icon-size" />
wrap the code in a code tag

2022-11-10 19:17 UTC, juliodialpad commented on migration_guide/MIGRATION_GUIDE.md
> +[Dialtone Vue - Icon component](https://vue.dialpad.design/?path=/story/components-icon--default)
I'll need to update dialtone-icons to include the svg files too, so they can import svg's from dialtone-icons repo.

2022-11-10 19:28 UTC, francisrupert requested changes
Great start, particularly the migration guide.

Two key things I don't see fully complete yet, though I'm guessing they're still in progress.

* Some instances of `.d-svg` remain within components. I won't list them all, but a few examples: Chip, Notice, Modal.
* Updating CSS to no longer _contextually resize_, e.g. `.d-btn--sm .d-btn__icon .d-svg {width: [size]; height: [size]; }`

2022-11-10 19:28 UTC, francisrupert commented on docs/.vuepress/theme/components/Navbar.vue
> +            class="d-icon d-icon--size-400"
Oh, we don't have a `<dt-icon>` for Github and Codepen. That's cool. Good catch on at least using `.d-icon` and `d-icon--size-400`.

2022-11-10 19:28 UTC, francisrupert commented on migration_guide/MIGRATION_GUIDE.md
> +- Deprecated .d-svg class
Update to something like...

> Deprecated .d-svg class associated with the previous Material Design icon set. The previous icon set will remain available until it is sunset upon complete adoption.

2022-11-10 19:28 UTC, francisrupert commented on migration_guide/MIGRATION_GUIDE.md
> +#### Replace icons with dialtone-vue icon component if possible
Make it clear that any non-Vue use of an icon can be updated with the raw HTML equivalent, i.e. 
`<svg class=" d-icon   d-icon--size-[SIZE]  d-icon--[ICON_NAME]....`"

2022-11-10 19:28 UTC, francisrupert commented on migration_guide/MIGRATION_GUIDE.md
> +Remove any usage of `d-svg` and `d-svg--*`.
Need a note for any _custom CSS_ products may have done locally. That is, remove any contextual sizing of the icon in favor of only use Vue's `size` prop or (for raw HTML usage) the `d-icon--size-NNN`. For example, no longer can do something like `.foo .icon { width: xxx; height: yyy; }`.

Markdown section as ...
```
#### Product custom CSS
```

2022-11-10 19:31 UTC, francisrupert commented
@juliodialpad, @braddialpad What do you think of pulling out the Migration Guide to its own PR and release that to Production just to get it out there?

2022-11-10 19:35 UTC, braddialpad commented
> @juliodialpad, @braddialpad What do you think of pulling out the Migration Guide to its own PR and release that to Production just to get it out there?

If @juliodialpad thinks the additional changes will take a while then yes. Though it sounds like he still needs to make some changes to dialtone-icons before releasing the migration guide.

2022-11-10 19:39 UTC, juliodialpad commented
> > @juliodialpad, @braddialpad What do you think of pulling out the Migration Guide to its own PR and release that to Production just to get it out there?
> 
> If @juliodialpad thinks the additional changes will take a while then yes. Though it sounds like he still needs to make some changes to dialtone-icons before releasing the migration guide.

Yes, I'll need to add svg icons to dialtone-icons, I'll create a PR to that ASAP.

2022-11-10 22:27 UTC, francisrupert reviewed
@juliodialpad I made comments directly on the **commit** by accident, but forgot they wouldn't appear as a review comment.

In case you weren't alerted to them, you can see them at https://github.com/dialpad/dialtone/commit/ac70a4aa78333014f750a342e26c41ce1de551dd

2022-11-11 16:47 UTC, juliodialpad commented
> Great start, particularly the migration guide.
> 
> Two key things I don't see fully complete yet, though I'm guessing they're still in progress.
> 
> * Some instances of `.d-svg` remain within components. I won't list them all, but a few examples: Chip, Notice, Modal.
> * Updating CSS to no longer _contextually resize_, e.g. `.d-btn--sm .d-btn__icon .d-svg {width: [size]; height: [size]; }`

I didn't removed that CSS because it will break all the styling in the app, I prefer to maintain the styling until the icons are fully migrated, that way, the migration can be released iteratively and don't need to do it all at a time.

2022-11-11 17:40 UTC, francisrupert commented
> I didn't removed that CSS because it will break all the styling in the app, I prefer to maintain the styling until the icons are fully migrated, that way, the migration can be released iteratively and don't need to do it all at a time.

Yeah, great point. Removing that CSS assumes 100% adoption of the new icons. Can you capture a backlog task so we can iteratively follow through on it.

2022-11-11 18:34 UTC, juliodialpad commented
> > I didn't removed that CSS because it will break all the styling in the app, I prefer to maintain the styling until the icons are fully migrated, that way, the migration can be released iteratively and don't need to do it all at a time.
> 
> Yeah, great point. Removing that CSS assumes 100% adoption of the new icons. Can you capture a backlog task so we can iteratively follow through on it.

Sure, I'll do it

2022-11-11 21:33 UTC, francisrupert approved these changes

2022-11-12 00:00 UTC, merged