docsite: add search by icon name in icon component
dialpad/dialtone-legacy pull request #744
Opened 2022-11-22 22:05 UTC by josedialpad

## Description
Jira ticket: https://dialpad.atlassian.net/browse/DT-754

First iteration adding icon search by name.

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

## Obligatory GIF (super important!)
![](https://i.giphy.com/media/26n6WywJyh39n1pBu/giphy.webp)

2022-11-22 23:32 UTC, francisrupert requested changes
Liking.

2022-11-22 23:32 UTC, francisrupert commented on docs/.vuepress/views/IconCatalog.vue
> +        />
Wrap with a `<button>`, unstyled so it doesn't change appearance, and `@click` to it.

2022-11-22 23:32 UTC, francisrupert commented on docs/.vuepress/views/IconCatalog.vue
> +        <icon-x-circle
Change to use icon "Close"

<img width="561" alt="image" src="https://user-images.githubusercontent.com/1165933/203439529-91f633d1-f7ae-4345-b2d8-699a48d5fd2d.png">

2022-11-22 23:32 UTC, francisrupert commented on docs/.vuepress/views/IconCatalog.vue
> +    <div class="d-gc2 d-select">
DIsable the `<option>` items that don't have a result.

<img width="966" alt="image" src="https://user-images.githubusercontent.com/1165933/203440600-560db6f1-2a96-4b95-baaa-6ac3b34ee4bb.png">

2022-11-22 23:32 UTC, francisrupert commented on docs/.vuepress/views/IconCatalog.vue
> +          @click="resetSearch"
Clicking on reset should also reset the `<select>` choice back to "All categories."

2022-11-22 23:45 UTC, braddialpad commented on docs/.vuepress/views/IconCatalog.vue
> +const searchDebounced = refDebounced(search, 500);
The debounce makes it feel a bit sluggish, I'm not sure we need it since we're not making any API request

2022-11-22 23:45 UTC, braddialpad commented on docs/.vuepress/views/IconCatalog.vue
> +      >
We can probably just make this not search unless 2 characters are entered and remove the debounce. I think the 2 character minimum was in the keyword search story, but probably should have been in this one.

2022-11-22 23:50 UTC, braddialpad commented on docs/.vuepress/views/IconCatalog.vue
> +      >
Remember that we can use Dialtone Vue components in this repo now. Probably can just use dt-input here. Don't even need to import can just use `<dt-input>` directly in the template.

2022-11-24 00:05 UTC, josedialpad commented on docs/.vuepress/views/IconCatalog.vue
> +        />
Updated using muted `dt-button`

2022-11-24 00:05 UTC, josedialpad commented on docs/.vuepress/views/IconCatalog.vue
> +        <icon-x-circle
Updated 👍

2022-11-24 00:06 UTC, josedialpad commented on docs/.vuepress/views/IconCatalog.vue
> +    <div class="d-gc2 d-select">
Good call, updated the category filter to works with the search results.

2022-11-24 00:06 UTC, josedialpad commented on docs/.vuepress/views/IconCatalog.vue
> +          @click="resetSearch"
Updated to reset category too

2022-11-24 00:07 UTC, josedialpad commented on docs/.vuepress/views/IconCatalog.vue
> +const searchDebounced = refDebounced(search, 500);
Yeah, wanted to prevent filtering multiple times due to fast type but feels laggy. So removed the debounce

2022-11-24 00:08 UTC, josedialpad commented on docs/.vuepress/views/IconCatalog.vue
> +      >
Updated to search with the minimum character only and removed the debounce

2022-11-24 00:09 UTC, josedialpad commented on docs/.vuepress/views/IconCatalog.vue
> +      >
Right, udpated to use `dt-input`

2022-11-24 00:26 UTC, braddialpad commented on docs/.vuepress/views/IconCatalog.vue
>    >
Might want to put some kind of "empty" placeholder in here when no results are returned by the search. Other than that looks good 👍 

ex: 
![Screenshot 2022-11-23 at 4 22 56 PM](https://user-images.githubusercontent.com/64808812/203667810-08d97d33-b905-4839-921a-cdf1993bd3ce.png)

2022-11-24 15:44 UTC, josedialpad commented on docs/.vuepress/views/IconCatalog.vue
>    >
Good call, added that empty list message and also the input placeholder

2022-11-24 16:03 UTC, braddialpad approved these changes

2022-11-24 16:08 UTC, merged