More omnichannel brand icons
dialpad/dialtone-legacy pull request #750
Opened 2022-11-28 20:29 UTC by tedgoas-dialpad

## Description
Adding brand icons for future omnichannel integrations:
Telegram, WeChat, Google Business Messaging, LINE, Viber, TikTok, Snapchat

DP-49152

## Obligatory GIF (super important!)
![giphy-2](https://user-images.githubusercontent.com/65190890/204374556-879af0ac-42ed-4d64-b3a7-5e0dfff8122a.gif)

2022-11-28 22:15 UTC, braddialpad requested changes

2022-11-28 22:15 UTC, braddialpad commented on docs/_data/svg-brand.json
> +    "vue": "IconWeChat",
The WeChat icon isn't showing up in the preview. The PascalCase name here is derived from the svg filename on build capitalizing the first character after the `-`. To fix this either:

1. Change this line to `IconWechat`
2. Change the svg file name to `we-chat.svg`

2022-11-28 22:27 UTC, tedgoas-dialpad commented on docs/_data/svg-brand.json
> +    "vue": "IconWeChat",
Ahh, I didn't know that's how it worked! Just pushed the change.

2022-11-28 22:52 UTC, braddialpad commented
Looks like you updated the json correctly, but missed fixing the filename itself (from wechat.svg to we-chat.svg)

2022-11-29 17:17 UTC, braddialpad approved these changes
Looks great!

2022-12-01 19:12 UTC, merged