docs: automate components overview build
dialpad/dialtone-legacy pull request #764
Opened 2022-12-08 00:21 UTC by juliodialpad

## Description

- Added script to get the frontmatter information from '/components/' path.
- Automated the building of /components/ overview.

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [ ] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

## Obligatory GIF (super important!)
![](https://media.giphy.com/media/1BdJd24oEwvuSvXYb0/giphy.gif)

2022-12-08 21:21 UTC, francisrupert requested changes
Loving this so much.

Since you have it tied directly to Commponents `index.md` how do we reuse it on other landing pages? https://dialpad.design/design/ and https://dialpad.design/guides/

Note I previously added a `"planned": true` placeholder in `site-nav.json as a way to get it in the left nav. So that's redundancy on my part, how can we reconcile? I like that it's in the front matter, can that be reused for the left-nav, or should it solely be in `site-nav.json` or...?

<img width="176" alt="image" src="https://user-images.githubusercontent.com/1165933/206569928-aaf4202a-845d-4261-a640-f0b8b3120f42.png">

2022-12-08 21:21 UTC, francisrupert commented on docs/_data/site-nav.json
> +          "text": "Select Menu",
Any particular reason this was renamed?

2022-12-08 21:21 UTC, francisrupert commented on docs/components/index.md
> +  <router-link
Will need to account for items listed here, but don't yet have a page. Look at https://dialpad.design/design/ for example...

```html

<div class="dialtone-wall__item dialtone-wall__item--disabled"...
```
or
```html

<router-link class="dialtone-wall__item"...

```

2022-12-08 21:21 UTC, francisrupert commented on docs/components/index.md
> +    <div class="dialtone-wall__image">
Suppress if no image available, which currently occurs on https://dialpad.design/design/ and https://dialpad.design/guides/

2022-12-08 21:21 UTC, francisrupert commented on docs/components/index.md
> +};
We'll probably have more badge types once I figure out strategy for component health. At least for now, make "Ready" as `d-badge--success` (green).

2022-12-08 23:10 UTC, juliodialpad commented on docs/_data/site-nav.json
> +          "text": "Select Menu",
Yes, `Select menu` is the "right" naming, is was called that way in everywhere else except of that file, so I wanted to keep the aligned.

2022-12-08 23:11 UTC, juliodialpad commented on docs/_data/site-nav.json
> +          "text": "Select Menu",
Dialtone-vue: https://vue.dialpad.design/?path=/story/components-select-menu--default
Dialtone: 
![Screenshot 2022-12-08 at 5 11 08 p m](https://user-images.githubusercontent.com/87546543/206586351-8ff441b4-632d-4337-9010-f6aa5a425791.png)

Also in dialtone was called that way, but not on the sidebar and file.

2022-12-08 23:38 UTC, francisrupert commented on docs/_data/site-nav.json
> +          "text": "Select Menu",
Ah, ok. Meanwhile: sentence case to "Select menu"

2022-12-09 06:01 UTC, juliodialpad commented on docs/components/index.md
> +  <router-link
Sure, I noticed I was doing it the wrong way...

I'm working now on a more universal component to render them all.

2022-12-09 14:58 UTC, francisrupert requested changes

2022-12-09 14:58 UTC, francisrupert commented on docs/_data/site-nav.json
>            "text": "Getting Started",
"Getting started" (sentence case).

2022-12-09 14:58 UTC, francisrupert commented on docs/.vuepress/views/Overview.vue
> +<template>
Love this `Overview.vue` for reuse 🤩

2022-12-09 14:58 UTC, francisrupert commented on docs/_data/site-nav.json
> +          "link": "/guides/getting_started/"
Any particular reason for changing to underscore? Tad bit of concern on breaking existing links (e.g. bookmarks, etc.). Internal links are thrown around and a lot in Slack, DP, emails, etc and we'll be throwing 404s at everyone.

2022-12-09 14:58 UTC, francisrupert commented on docs/_data/site-nav.json
> +          "text": "Accessibility and inclusive design",
Let's change this to just "Accessibility." 

<img width="245" alt="image" src="https://user-images.githubusercontent.com/1165933/206729574-c80be06d-eb73-4d7f-9014-06c15a4ec944.png">

2022-12-12 16:59 UTC, juliodialpad commented on docs/_data/site-nav.json
> +          "link": "/guides/getting_started/"
Had to chance some links...

Now that we are building some stuff automatically (sidebar, prev and next links, overview) We need to have a standard naming convention so I needed to decide if we wanted to stay with underscore or score case, so I decided to stay with "score-case" but many links were not conforming with that so they had to be renamed.

2022-12-12 17:01 UTC, juliodialpad commented on docs/_data/site-nav.json
> +          "text": "Accessibility and inclusive design",
Renamed but added a "hack" to maintain it that way...

The naming in the sidebar, must match the Title in the frontmatter and the url... so we need to add a `shortTitle` property to the frontmatter to get around this.

2022-12-12 19:53 UTC, francisrupert approved these changes
Great updates. Approved with one tiny change request.

2022-12-12 19:53 UTC, francisrupert commented on docs/guides/content/index.md
> +shortTitle: content
Like the `shortTitle` approach, though keep this one as "Writing guidelines".

2022-12-12 20:04 UTC, juliodialpad commented on docs/guides/content/index.md
> +shortTitle: content
Renamed

2022-12-12 20:04 UTC, juliodialpad commented
@braddialpad any comment on the technical side here? or is it good to go?

2022-12-12 20:44 UTC, braddialpad commented
Having a look

2022-12-12 20:52 UTC, braddialpad approved these changes
Very nice thanks

2022-12-12 21:01 UTC, merged