docs(icon): refactor popover
dialpad/dialtone-legacy pull request #781
Opened 2023-01-07 00:35 UTC by juliodialpad

## Description

Rebuilt icon popover to use `dt-popover` and improve accessibility and overall look.

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [ ] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

## Obligatory GIF (super important!)
![](https://media.giphy.com/media/DKnMqdm9i980E/giphy.gif)

2023-01-13 19:56 UTC, francisrupert requested changes
This popover rocks. Great job getting it built! A few tiny formatting changes called out on specific lines. And then a few not viewable in code diff:

* Change `class="d-popover__header d-pl24"` to `class="d-popover__header d-pl16"`.
* Change `class="d-popover__content d-p24"` to `class="d-popover__content d-p16"`

I provisionally approve from design perspective, defer to @braddialpad and @josedialpad for everything else.

2023-01-13 19:56 UTC, francisrupert commented on docs/.vuepress/baseComponents/IconPopoverContent.vue
> +        <span class="d-fc-disabled">Name</span>
Change to `class="d-label d-label--sm"`

2023-01-13 19:56 UTC, francisrupert commented on docs/.vuepress/baseComponents/IconPopoverContent.vue
> +      <span class="d-fc-disabled">Category</span>
Change to `class="d-label d-label--sm"`

2023-01-13 19:56 UTC, francisrupert commented on docs/.vuepress/baseComponents/IconPopoverContent.vue
> +      <span class="d-fc-disabled">Keywords</span>
Change to `class="d-label d-label--sm"`

2023-01-13 19:56 UTC, francisrupert commented on docs/.vuepress/baseComponents/IconPopoverContent.vue
> +  <div class="d-d-flex d-ai-center d-fl-center d-h64 d-mb24">
Change `d-mb24` to `d-mb16`

2023-01-13 19:56 UTC, francisrupert commented on docs/.vuepress/baseComponents/IconPopoverContent.vue
> +          size="sm"
Add `class="d-ff-mono"`

2023-01-13 19:56 UTC, francisrupert commented on docs/.vuepress/baseComponents/IconPopoverContent.vue
> +          size="sm"
Add `class="d-ff-mono"`

2023-01-13 21:34 UTC, braddialpad reviewed
Great work!

2023-01-13 21:34 UTC, braddialpad commented on docs/.vuepress/baseComponents/IconPopover.vue
> +    :modal="true"
Hmm something weird happening with the modality on this.. I'm not able to scroll the page which is correct, but I am able to mouseover and click items outside the modal. Is the invisible overlay possibly not working on the docsite?

2023-01-13 21:34 UTC, braddialpad commented on docs/.vuepress/baseComponents/IconPopoverContent.vue
> +        class="d-ml8"
can set a copy aria-label on these copy buttons to say specifically what they are copying (ex: copy name, copy SVG markup, copy vue markup)

2023-01-13 21:34 UTC, braddialpad commented on docs/.vuepress/views/IconCatalog.vue
>  };
Lets comment this a bit, it's pretty complex.

2023-01-13 21:34 UTC, braddialpad commented on docs/.vuepress/views/IconCatalog.vue
> +  }, 300);
We should make a debounce utility function for this https://www.freecodecamp.org/news/javascript-debounce-example/

2023-01-16 19:52 UTC, juliodialpad commented on docs/.vuepress/baseComponents/IconPopover.vue
> +    :modal="true"
Looks like it wasn't working due to the `d-modal--transparent` element didn't had a proper sizing. 

Will add a fix for this making the overlay full screen.

![Screenshot 2023-01-16 at 1 44 19 p m](https://user-images.githubusercontent.com/87546543/212755216-6df20f20-8634-4341-9a40-cfd8828a17e0.png)

2023-01-17 17:27 UTC, braddialpad approved these changes
Thanks!

2023-01-17 17:27 UTC, francisrupert approved these changes

2023-01-17 17:28 UTC, francisrupert commented
Awesome. Merge away!

2023-01-17 17:39 UTC, merged