POC: components health status
dialpad/dialtone-legacy pull request #809
Opened 2023-02-02 01:00 UTC by juliodialpad

## Description

Created a POC with components health status page, added documentation about the frontmatter properties we are using.

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

## Obligatory GIF (super important!)
![](https://media.giphy.com/media/gLREH1v1Z78tJckuii/giphy.gif)

2023-02-02 15:30 UTC, iropolo commented on docs/.vuepress/theme/index.js
>      .sort((a, b) => sortingArr.indexOf(a.link) - sortingArr.indexOf(b.link));
I suggest to split these code and create sth like

const pathPages = getPagePath(whatever, 'path');
const pathPagesFiltered = getHtmlPages(pathPages);
const htmlFrontmatterPages = getFrontmatter(pathPagesFiltered);
const htmlFrontmatterPagesFormated = set....
const sorted..... = sort....

Create a folder called utils and move those function there.

It will be more readable and scalable.
Apply this for the following code.

If `blogPostsFrontmatter` , `extractFrontmatter` , `extractComponentStatus` are local functions and they will not be exported, I would refactor those with _ on the beggining or move them to util foolder.

This are just suggestions and it is not necessary to be applied at this moment. :)

2023-02-02 15:32 UTC, iropolo commented
I really like this POC :)

2023-02-02 18:00 UTC, braddialpad reviewed
Really awesome! I think we can probably just release this to production and then update when Francis is done with the final designs.

2023-02-02 18:00 UTC, braddialpad commented on docs/.vuepress/theme/index.js
> +  const indexPage = app.pages.find(page => page.path === '/components/status/');
While we're at it we might as well create new pages for our two planned components this quarter "Emoji Picker" and "Infinite Scroll".

2023-02-02 18:00 UTC, braddialpad commented on .github/CONTRIBUTING.md
> +  if status is not defined, the components will have a 'No implemented Yet' status.
"Not implemented yet"

2023-02-02 18:00 UTC, braddialpad commented on docs/.vuepress/theme/index.js
> +        css: componentStatus(frontmatter.status),
I think for components such as "list-item" and "dropdown" that are vue only components and have no styles in dialtone we should set this to "not yet implemented".

2023-02-02 20:17 UTC, francisrupert requested changes
Yeah, this is awesome and I don't see much reason not to MVP release it. I'll eventually take some time for detailed feedback, but in the meantime:

* Page title: "Component status" (sentence case)
* I'm assuming the buttons are for filtering. I'll propose a UI for that later, so perhaps an MVP version of this doesn't have that functionality. In lieu of that, just list the icon/label pairing inline.
* The values you got from that old Confluence page is out-of-date. I started to effectively replace it with this [Spreadsheet](https://docs.google.com/spreadsheets/d/1mjQDvWAVAZV_qL6xmceu4WLeq7ZVimxWvzDDpUmooAE/edit#gid=0). 
  * Reconcile where you can can, and I'll validate through an updated PR. (ignore the columns for docs, a11y, iOS, Android.
* Reserve columns for Introduced/Modified version numbers, which we have separate task for.
* Change "Available" to "Ready"
* Change "Not implemented yet" with "Planned"
* Change "Work in progress" to "In progress"
* Add another value of "N/A". for example, a Figma file for "Lazy show" doesn't apply
* Make sure each table data cell has accessible equivalent of its value, e.g. "Ready / In progress / etc"

2023-02-03 03:27 UTC, juliodialpad commented on docs/.vuepress/theme/index.js
>      .sort((a, b) => sortingArr.indexOf(a.link) - sortingArr.indexOf(b.link));
Nice suggestion!

I'll add the underscore at the beginning cause this are local functions and we are not going to reuse it anywhere else, so I prefer to maintain them here.

Maybe a refactor could be done later as I notice I have some repeated code, but nothing too bad.

2023-02-03 03:29 UTC, juliodialpad commented on docs/.vuepress/theme/index.js
> +  const indexPage = app.pages.find(page => page.path === '/components/status/');
Sure! Will do

2023-02-03 03:34 UTC, juliodialpad commented on docs/.vuepress/theme/index.js
> +        css: componentStatus(frontmatter.status),
Sure, we only need to remove the `status` property from this components and will have that state or do you think it's a better pattern to set `status: NYI` to be more clear about the intention?

2023-02-03 04:27 UTC, juliodialpad commented
> * I'm assuming the buttons are for filtering. I'll propose a UI for that later, so perhaps an MVP version of this doesn't have that functionality. In lieu of that, just list the icon/label pairing inline.
Sure! Will do

> * The values you got from that old Confluence page is out-of-date. I started to effectively replace it with this [Spreadsheet](https://docs.google.com/spreadsheets/d/1mjQDvWAVAZV_qL6xmceu4WLeq7ZVimxWvzDDpUmooAE/edit#gid=0).
>   
>   * Reconcile where you can can, and I'll validate through an updated PR. (ignore the columns for docs, a11y, iOS, Android.
In fact, the values are being retrieved directly from the components frontmatter so they should be updated... I'll check the new list to see if there's any difference.

> * Reserve columns for Introduced/Modified version numbers, which we have separate task for.
Do you want me to add the columns now and leave them empty or just have in mind that we are adding new columns?


> * Add another value of "N/A". for example, a Figma file for "Lazy show" doesn't apply
Nice addition! Will add this.

> * Make sure each table data cell has accessible equivalent of its value, e.g. "Ready / In progress / etc"
Added `aria-label` and `tabindex=0` properties.

2023-02-03 04:31 UTC, juliodialpad commented on docs/.vuepress/theme/index.js
> +        css: componentStatus(frontmatter.status),
Changed `list-item` and `dropdown` statuses to: planned.

2023-02-03 04:43 UTC, juliodialpad commented
@francisrupert The way I thought this is:

- If `figma` property is a URL: the component health status is "ready"... moving such component to `in progress` will remove the Figma button from the component page.

The same logic applies to `storybook` property.

I made it this way because it's simpler to have one property and make validations instead of having a lot of properties, e.g:

```md
---
status: ready
storybook: https://vue.dialpad.design/...
figma: https://www.figma.com/file/...
---
```

vs

```md
---
status: ready
storybook: ready
storybook_url: status: ready
figma: in progress
figma_url: https://www.figma.com/file/...
---
```

2023-02-07 13:03 UTC, iropolo commented
LGTM! 🚀

2023-02-07 15:31 UTC, francisrupert requested changes
Here are updated values for Figma column. 

<img width="500" alt="image" src="https://user-images.githubusercontent.com/1165933/217289821-eaaab90d-a7c4-476d-81a8-e5a583e05538.png">

2023-02-07 17:23 UTC, juliodialpad commented
> Here are updated values for Figma column.
> 
> <img alt="image" width="500" src="https://user-images.githubusercontent.com/1165933/217289821-eaaab90d-a7c4-476d-81a8-e5a583e05538.png">

Can you please provide the link to `validation messages` Figma? I couldn't find it.

2023-02-07 18:56 UTC, francisrupert approved these changes

2023-02-07 18:56 UTC, francisrupert commented on docs/components/validation-messages.md
> +storybook: https://vue.dialpad.design/?path=/story/components-validation-messages--default
Figma link https://www.figma.com/file/2adf7JhZOncRyjYiy2joil/DT-Core%3A-Components-7?node-id=11399%3A76354&t=LqzEvQfr3DMHh7Og-11

2023-02-07 19:32 UTC, merged