feat(stack): stack component styles
dialpad/dialtone-legacy pull request #827
Opened 2023-02-15 21:18 UTC by iropolo

## Description

- Added stack component styles

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

2023-02-15 21:24 UTC, braddialpad requested changes
Looks good, but you'll need to do a stack component documentation page as well. You can do this in a separate PR if you wish.

2023-02-15 21:37 UTC, iropolo commented
> Looks good, but you'll need to do a stack component documentation page as well. You can do this in a separate PR if you wish.

Ye, working on it now, I realized after created the PR

2023-02-16 00:36 UTC, braddialpad commented on lib/build/less/components/stack.less
> +}
You can just put .direction-options() within .d-stack also. It will generate d-stack--column, but I don't really think that hurts anything.

2023-02-16 15:20 UTC, iropolo commented on lib/build/less/components/stack.less
> +}
Mhmm good to know but anyways d-stack--column it is not necessary so I would let it at this way

2023-02-16 20:53 UTC, braddialpad commented on docs/_data/stack.json
> +    },
On their own these classes don't actually do anything right?

I think we'll need to document all the combinations.

`d-stack--xl--column`
`d-stack--xl--column-reverse`
`d-stack--xl--row`
`d-stack--xl--row-reverse`
`d-stack--lg--column`
`d-stack--lg--row`
...and so on

Tedious I know..

2023-02-16 21:09 UTC, iropolo commented on docs/_data/stack.json
> +    },
Mhmm, this is wym? 🤔

2023-02-16 21:14 UTC, braddialpad commented on docs/_data/stack.json
> +    },
yep exactly, thanks

2023-02-16 21:15 UTC, braddialpad commented on docs/components/stack.md
> +status: new
set status to beta

2023-02-16 21:50 UTC, braddialpad approved these changes

2023-02-16 23:52 UTC, merged