docs: fix page toc
dialpad/dialtone-legacy pull request #862
Opened 2023-04-07 19:21 UTC by juliodialpad

## Description

- Added back the functionality of `active` item.
- Fixed the position of the `page-toc` it was no longer being fixed on page.
- Fixed the responsive version of `page-toc`
- Fixed the `scroll-padding-top` on responsive version of the site.

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [ ] Update, remove, or extend all affected documentation.
 - [ ] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

## Obligatory GIF (super important!)
![](https://media.giphy.com/media/ThrM4jEi2lBxd7X2yz/giphy.gif)

2023-04-10 16:48 UTC, braddialpad commented
Looks like there's a problem with the positioning of the TOC when widescreen

before:
![Screenshot 2023-04-10 at 9 47 28 AM](https://user-images.githubusercontent.com/64808812/230949567-fd0cac80-2af1-46c6-a38a-9f9a9db12bd5.png)


after:
![Screenshot 2023-04-10 at 9 42 12 AM](https://user-images.githubusercontent.com/64808812/230949423-a7b464a9-deb8-4c4a-ac4e-b04280dc2b39.png)

2023-04-11 17:44 UTC, juliodialpad commented on docs/.vuepress/theme/assets/less/dialtone-docs.less
> +    overflow-y: unset !important;
Kind of hack because `dt-root-layout` component is adding a `d-of-y-auto` which doesn't let `d-ps-sticky` work correctly.

https://university.webflow.com/lesson/create-a-sticky-sidebar#:~:text=Troubleshooting%20position%20sticky,-Sometimes%2C%20position%20sticky&text=Position%20sticky%20will%20most%20probably,element%20has%20a%20set%20height.

2023-04-14 00:33 UTC, braddialpad commented on docs/.vuepress/theme/assets/less/dialtone-docs.less
> +    overflow-y: unset !important;
hmm yeah we have to rework root layout a bit. This is fine for now.

2023-04-14 00:37 UTC, braddialpad requested changes
Hmm seem to be getting some horizontal overflow at mobile size since the latest changes.
![Screenshot 2023-04-13 at 5 36 36 PM](https://user-images.githubusercontent.com/64808812/231912019-3b53ac09-be7a-4900-8d83-64f96124a646.png)

2023-04-14 20:36 UTC, juliodialpad commented
Didn't noticed that, thanks Brad! can fix that in two ways...
Do you have a preference over one?

Option 1:
![Screenshot 2023-04-14 at 2 34 24 p m](https://user-images.githubusercontent.com/87546543/232149618-9d535424-214b-45b3-80a5-860e7e36b7b5.png)

Option 2:
![Screenshot 2023-04-14 at 2 35 30 p m](https://user-images.githubusercontent.com/87546543/232149718-0776d90f-019c-486d-ba19-ffed0a3af164.png)

cc: @francisrupert

2023-04-14 21:24 UTC, braddialpad commented
I prefer option 2 looks a bit a bit less jumbled

2023-04-14 22:15 UTC, francisrupert commented
Option 2 is good for now. Not ideal but I'll look to finesse the mobile view at some point.

2023-04-14 22:16 UTC, juliodialpad commented
Right, option 2 is up, please give it another review.

2023-04-14 22:22 UTC, braddialpad approved these changes
Looks good!

2023-04-15 00:35 UTC, merged