feat: dialtone tokens -- dark mode
dialpad/dialtone-legacy pull request #880
Opened 2023-05-15 19:00 UTC by juliodialpad

## Description

- Extracted and generated **Dark** and **Light** colors and variables
- Added a simple Light/Dark toggle button
- Fixed the page-toc

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [ ] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [ ] Update, remove, or extend all affected documentation.
 - [ ] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

## Obligatory GIF (super important!)
![](https://media.giphy.com/media/hOjpSwqSVkJDG/giphy.gif)

2023-05-15 19:10 UTC, braddialpad commented on docs/.vuepress/theme/client.js
> +    document.body.classList.add('dialtone-theme-light');
```
[Vue warn]: Unhandled error during execution of setup function 
  at <VuepressApp>
✖ Rendering 143 pages - failed in 76ms
ReferenceError: document is not defined
```

Hmm this must execute before the dom is initialized? Maybe it can go in config.js? I see we set head tags in there is there something similar for body?

2023-05-15 19:11 UTC, braddialpad commented on docs/.vuepress/theme/client.js
> +    document.body.classList.add('dialtone-theme-light');
nm you already fixed it, haha

2023-05-15 19:12 UTC, juliodialpad commented on docs/.vuepress/theme/client.js
> +    document.body.classList.add('dialtone-theme-light');
I just fixed it, moved to a non SSR code block

2023-05-15 19:13 UTC, braddialpad commented
WOW SO COOL!

2023-05-15 19:13 UTC, juliodialpad commented on docs/.vuepress/theme/client.js
> +    document.body.classList.add('dialtone-theme-light');
> nm you already fixed it, haha

Yeah, that was quite a fast review 😂

2023-05-15 19:24 UTC, braddialpad requested changes
Looks great! Noticed a couple small things so far.

These buttons nearly disappear when in dark mode.
![2023-05-15 12 17 19](https://github.com/dialpad/dialtone/assets/64808812/87d368f6-e210-49e1-a108-f0a8093f1e8f)

Looks like the foreground color got messed up on our color palettes.
![Screenshot 2023-05-15 at 12 18 14 PM](https://github.com/dialpad/dialtone/assets/64808812/2e3022cd-cac4-422c-8697-207ceb4497bb)

Dark background looks kinda awkward on some of these examples... Maybe we just keep them all light for now?
![Screenshot 2023-05-15 at 12 19 16 PM](https://github.com/dialpad/dialtone/assets/64808812/2f90bca9-e7e5-4178-b804-c046da88ed02)

2023-05-15 19:30 UTC, iropolo commented
Nice job here :)

But the highlight code seems a little bit ugly, could we do sth different here? like how the codepen works?

Do we have the flexiblity to modified it?


![image](https://github.com/dialpad/dialtone/assets/89984179/e8ad3220-bbe2-43c2-8bd3-0038bb4d4071)

![image](https://github.com/dialpad/dialtone/assets/89984179/ec99c571-b639-43a5-8b00-34aa514f6fd3)

2023-05-15 19:45 UTC, braddialpad requested changes
I went through every page on the site now.

Couple more:

Some of these brand icons don't change.
![2023-05-15 12 36 43](https://github.com/dialpad/dialtone/assets/64808812/69f4f113-b9e6-481c-81ff-83c1a3bb6303)

Might just need to change to a different background color here, I can't see the shadow at all.
![Screenshot 2023-05-15 at 12 28 06 PM](https://github.com/dialpad/dialtone/assets/64808812/670c7e88-85b2-460a-ae88-3f6d266a79f9)

This red looks a bit off.
![Screenshot 2023-05-15 at 12 32 47 PM](https://github.com/dialpad/dialtone/assets/64808812/e6a082dd-b551-4e32-80ed-ea189e23d81f)

Is this blue link color intended? It sort of hurts my eyes when I look at it.
![Screenshot 2023-05-15 at 12 38 14 PM](https://github.com/dialpad/dialtone/assets/64808812/a9d78f6c-0635-4083-920b-6cd185fcede4)

Patterns don't look very good but I think we can get rid of these anyways...
![Screenshot 2023-05-15 at 12 40 15 PM](https://github.com/dialpad/dialtone/assets/64808812/44aad91b-622a-4130-8554-194283d0f2c3)

Copy button doesn't change.
![Screenshot 2023-05-15 at 12 41 25 PM](https://github.com/dialpad/dialtone/assets/64808812/73b25d22-8f7c-4666-9186-f50b26324e6c)

I don't really care about fixing this right now but algolia is still in light mode.
![Screenshot 2023-05-15 at 12 41 47 PM](https://github.com/dialpad/dialtone/assets/64808812/d678f249-2fd4-4e23-b338-4595132721c9)

2023-05-15 19:51 UTC, juliodialpad commented
> Looks great! Noticed a couple small things so far.
> 
> These buttons nearly disappear when in dark mode. ![2023-05-15 12 17 19](https://user-images.githubusercontent.com/64808812/238452372-87d368f6-e210-49e1-a108-f0a8093f1e8f.gif)

Those icons should be added into dialtone-icons to make a migration, right now I'm using an `img` with `src='file.svg'` as a workaround for those missing icons. 

> Looks like the foreground color got messed up on our color palettes. ![Screenshot 2023-05-15 at 12 18 14 PM](https://user-images.githubusercontent.com/64808812/238452460-2e3022cd-cac4-422c-8697-207ceb4497bb.png)

Nice catch, fixing it.

> Dark background looks kinda awkward on some of these examples... Maybe we just keep them all light for now? ![Screenshot 2023-05-15 at 12 19 16 PM](https://user-images.githubusercontent.com/64808812/238452614-2f90bca9-e7e5-4178-b804-c046da88ed02.png)

Yeah, I can make them all white until we have images with transparent backgrounds or something like that.

2023-05-15 19:59 UTC, juliodialpad commented
> Looks like the foreground color got messed up on our color palettes. ![Screenshot 2023-05-15 at 12 18 14 PM](https://user-images.githubusercontent.com/64808812/238452460-2e3022cd-cac4-422c-8697-207ceb4497bb.png)

This will need more work in order to fix it...

Light
![Screenshot 2023-05-15 at 1 55 23 p m](https://github.com/dialpad/dialtone/assets/87546543/5594463c-2cef-44d8-8804-1f0069226f47)

Dark
![Screenshot 2023-05-15 at 1 58 29 p m](https://github.com/dialpad/dialtone/assets/87546543/c1403d22-578e-4b55-8a5b-d6d2b4d10c94)

I think we need to divide this list into Dark and Light Colors, this is so confusing right now.

2023-05-15 20:00 UTC, francisrupert commented
> looks kinda awkward on some of these examples... Maybe we just keep them all light for now?
> ![Screenshot 2023-05-15 at 12 19 16 PM](https://user-images.githubusercontent.com/64808812/238452614-2f90bca9-e7e5-4178-b804-c046da88ed02.png)

Images were updated on https://github.com/dialpad/dialtone/pull/874. They're currently transparent, and that PR updates them to be solid bg color. Better, but not ideal. In the future we'll probably toggle the image src too, e.g. 

```html
<picture>
  <source srcset="dark-mode.png" media="(prefers-color-scheme: dark)">
  <img src="light-image.png">
</picture>
```

2023-05-15 20:05 UTC, braddialpad commented
> I think we need to divide this list into Dark and Light Colors, this is so confusing right now.

Ahhh yeah I guess different colors need to change in dark mode, you can't just reverse.

2023-05-15 20:06 UTC, braddialpad commented on docs/.vuepress/theme/components/Navbar.vue
> +      </dt-button>
Hmm thinking this might be nice as a DtToggle

2023-05-15 20:18 UTC, francisrupert commented on docs/.vuepress/theme/components/Navbar.vue
> +      </dt-button>
For now, let's swap out the icon between `<dt-icon name="sun" />` and `<dt-icon name="moon" />`.

2023-05-15 20:34 UTC, francisrupert commented
Dang this is too satisfying the see. One key thing that's clear to me:

A lot of the color discrepancies in dark mode will be down to updating the **local CSS variables**. Many are accounted for in [the spreadsheet](https://docs.google.com/spreadsheets/d/1EZbvaM4A3_sTQ3pT6ejib__0m-QUyZkMItENSmgQGXQ/edit#gid=0) shared last week. But more pointedly are that next layer of semantic tokens used by _some_ of the components e.g. `action`, `inputs`, `badge`, etc.

[Input](https://www.figma.com/file/2adf7JhZOncRyjYiy2joil/DT-Core%3A-Components-7?type=design&node-id=8923-21866&t=dsJee9xQETEQRSLG-11) example:

```
--input-color-background: hsla(var(--dt-color-black-900-hsl) / .03);
```

...would become...

```
--input-color-background: var(--dt-inputs-color-background-default);
```

2023-05-16 17:24 UTC, braddialpad commented
Home page has some contrast issues.

![Screenshot 2023-05-16 at 10 22 58 AM](https://github.com/dialpad/dialtone/assets/64808812/24631797-6a73-445c-a0a5-c2b6f402aff5)

2023-05-16 17:46 UTC, francisrupert commented
> Home page has some contrast issues.

@juliodialpad, Don't take any action on homepage as we're probably going to outright redesign it.

Although... that background logomark is an SVG and its `fill` property can probably be replaced with a variable. Take a few minutes to play around with the tan base colors and see how it plays, e.g. `var(--tan-300)`

2023-05-17 19:31 UTC, juliodialpad commented
> Nice job here :)
> 
> But the highlight code seems a little bit ugly, could we do sth different here? like how the codepen works?
> 
> Do we have the flexiblity to modified it?
> 
> ![image](https://user-images.githubusercontent.com/89984179/238453905-e8ad3220-bbe2-43c2-8bd3-0038bb4d4071.png)
> 
> ![image](https://user-images.githubusercontent.com/89984179/238453948-ec99c571-b639-43a5-8b00-34aa514f6fd3.png)

Not the prettiest but I think is readable for now.

![Screenshot 2023-05-17 at 1 30 55 p m](https://github.com/dialpad/dialtone/assets/87546543/edebe813-6bfa-4345-a832-636351f367f0)

2023-05-18 17:34 UTC, juliodialpad commented
OK I fixed almost all the issues I could found, still have work to do, but I think this is really good enough to review.

Known stuff missing: 
- Colors Base palette
- Components preview image (will be update on #867) 
- Migration to semantic colors

2023-05-18 17:52 UTC, braddialpad commented on docs/.vuepress/theme/components/Navbar.vue
> +      </dt-button>
hmm seeing this live I'm not exactly sure the way this should go.

When you are in light mode should the icon show a moon meaning that by clicking that button you are changing it to dark mode? Or should it display a sun because you are currently in light mode and it reflects the state you are currently in? I think I lean towards the former.

2023-05-18 17:55 UTC, juliodialpad commented on docs/.vuepress/theme/components/Navbar.vue
> +      </dt-button>
This is the same way as [vuepress](https://v2.vuepress.vuejs.org/) is doing it. It feels natural to me that the button reflects the state you're currently on.

2023-05-18 17:57 UTC, braddialpad approved these changes
Looks like all my requested issues have been fixed.

The code examples definitely look too light for dark mode, but are easy enough to read, we can figure that out later.

Pre-approving for when:

- we come to a decision on the light/dark mode button state
- your prior mentioned remaining issues have been fixed.

2023-05-18 20:32 UTC, juliodialpad commented
I'd prefer to merge this one and create open up another one.

Fixing **Colors Base palette** isn't going to be a small change so I'd prefer to keep it separate as well as **Semantic colors migration**.

The button state can be fixed if needed on that PR too.

Are you OK with this @braddialpad?

2023-05-18 20:33 UTC, braddialpad commented
> I'd prefer to merge this one and create open up another one.
> 
> Fixing **Colors Base palette** isn't going to be a small change so I'd prefer to keep it separate as well as **Semantic colors migration**.
> 
> The button state can be fixed if needed on that PR too.
> 
> Are you OK with this @braddialpad?

Yeah sounds good

2023-05-18 20:33 UTC, merged