feat(button): CSS variable remapping
dialpad/dialtone-legacy pull request #883
Opened 2023-05-24 19:59 UTC by juliodialpad

## Description

Remapped the button CSS variables to match the semantic tokens

**note:** missing `d-btn-circle` remapping.

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [ ] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [ ] Update, remove, or extend all affected documentation.
 - [ ] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

## Obligatory GIF (super important!)
![](https://media.giphy.com/media/yoJC2GnSClbPOkV0eA/giphy.gif)

2023-05-24 22:55 UTC, braddialpad approved these changes

2023-05-25 14:36 UTC, francisrupert requested changes
This is really well-done updating of local CSS variable values to `--dt-` variables.

The circle (and non-circle) icon-only ones are really just a simple update, what you've already done accounts for the variants so the changes I noted are solely about the _default_ circle colors when they don't have the extra `d-btn--foo`. That default is `muted`.

2023-05-25 14:36 UTC, francisrupert commented on lib/build/less/components/button.less
>  .d-btn--brand {
No Design Token for the branded ones. Neutral white is correct value, and then the bg color is determined by the custom ones managed locally. At least for those we won't branded buttons as design tokens.

2023-05-25 14:36 UTC, francisrupert commented on lib/build/less/components/button.less
> +    --button-color-text: var(--dt-color-black-800); // Missing color remapping
`action.color.foreground.muted.default`

2023-05-25 14:36 UTC, francisrupert commented on lib/build/less/components/button.less
> +        --button-color-text: var(--muted-color-hover); // Missing color remapping
`action.color.foreground.muted.hover`

2023-05-25 14:36 UTC, francisrupert commented on lib/build/less/components/button.less
> +        --button-color-background: hsla(var(--dt-color-black-800-hsl) ~' / ' 3%); // Missing color remapping
`action.color.background.muted.hover`

2023-05-25 14:36 UTC, francisrupert commented on lib/build/less/components/button.less
> +        --button-color-text: var(--dt-color-foreground-secondary); // Missing color remapping
`action.color.background.muted.active`

2023-05-25 14:36 UTC, francisrupert commented on lib/build/less/components/button.less
> +        --button-color-background: hsla(var(--dt-color-black-800-hsl) ~' / ' 9%); // Missing color remapping
`action.color.background.muted.active`

2023-05-25 14:36 UTC, francisrupert commented on lib/build/less/components/button.less
> +        --button-color-border: var(--dt-color-black-600); // Missing color remapping
`action.color.border.muted.outlined.default`

2023-05-25 21:47 UTC, francisrupert requested changes
Ship it! Hopefully doing so for others will be more apparent. The key will be inspecting the Figma components to see what semantic styles have been applied to them. I'd hoped to create mappings for all like I did with buttons, but that's almost redundant effort.

2023-05-25 21:49 UTC, juliodialpad commented
You ment to request changes again or hit the wrong button and it is approved?

2023-05-25 22:04 UTC, merged