fix: LESS vars migration
dialpad/dialtone-legacy pull request #885
Opened 2023-05-26 23:34 UTC by juliodialpad

## Description

As we removed completely the LESS variables, the script should migrate previous LESS variables to CSS ones.

Changed color migration script that was incorrectly replacing e.g `@black-100` with `@dt-color-black-100` instead of replacing it with `var(--dt-color-black-100)`.

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [ ] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [ ] Update, remove, or extend all affected documentation.
 - [ ] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

## Obligatory GIF (super important!)
![](https://media.giphy.com/media/3rgXBvnbXtxwaWmhr2/giphy.gif)

2023-05-27 00:04 UTC, braddialpad requested changes

2023-05-27 00:04 UTC, braddialpad commented on docs/.vuepress/theme/components/Home.vue
> +          <circle
hmm I know the linter did this but I kinda hate it... maybe we allow more properties per line?

how about

```
"vue/max-attributes-per-line": ["warn", {
  "singleline": {
    "max": 6
  },      
  "multiline": {
    "max": 1
  }
}]
```

probably revert this file back to its original form before you set this.

2023-05-27 00:06 UTC, braddialpad commented
script change itself looks good.

2023-05-29 14:45 UTC, juliodialpad commented on docs/.vuepress/theme/components/Home.vue
> +          <circle
I don't like it either, I'll try those settings

2023-05-29 15:42 UTC, merged