chore: dialtone 8 migration guide
dialpad/dialtone-legacy pull request #888
Opened 2023-06-01 03:27 UTC by juliodialpad

## Description

Added migration guide including script usage, recommendations and the list of manual CSS -> Design tokens remapping that are needed to be done after the migration.

**Included some missing colors migrations**

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [ ] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

## Obligatory GIF (super important!)
![](https://media.giphy.com/media/107QsHzZW54hJC/giphy.gif)

2023-06-01 16:53 UTC, braddialpad requested changes
Lookin great!

2023-06-01 16:53 UTC, braddialpad commented on migration_guide/Dialtone_8.md
> +example, RAW HEX values or CSS variables that are not semantically correct.
We may want to include an example of a common case where you would need to do this to better illustrate the difference between base / semantic tokens. Perhaps the case I mentioned to you yesterday `--dt-color-neutral-white` to `--dt-color-surface-primary` could work.

2023-06-01 16:53 UTC, braddialpad commented on migration_guide/Dialtone_8.md
> +```
I've run into many cases where I have a large folder of components and I only want to migrate a few of the files rather than all of them. In this case I just make a temporary folder called "to_convert", put the files in there, migrate, and then move them back. May want to include how to do this process since I would expect others will have the same question.

2023-06-01 16:53 UTC, braddialpad commented on migration_guide/Dialtone_8.md
> +```
We may want to convey a little more that you probably shouldn't run the whole script on the entire codebase all at once, but do one section of the UI, visually verify it and fix any issues and then move on to the next.

Maybe the steps should be like..

Run the script on the desired files for the piece of UI you wish to change
Verify the migration script changed files as expected
Replace css variables with semantic
visually verify the piece of UI you changed in light mode as well as dark mode, fix anything that is obviously off
share preview with a designer and make any further requested changes
make a PR to commit your changes
repeat all this for the next section of UI

2023-06-01 16:53 UTC, braddialpad commented on migration_guide/Dialtone_8.md
> +| `var(--gold-500)`  |     `var(--dt-color-foreground-warning)`     |                                      |
May may want to also mention if the actual CSS property is `color` it should be foreground, if the property is `background-color` it should be surface etc. I think you sort of imply that in the heading but we should make that more explicit so there is no confusion.

2023-06-01 23:17 UTC, juliodialpad commented on migration_guide/Dialtone_8.md
> +```
> I've run into many cases where I have a large folder of components and I only want to migrate a few of the files rather than all of them. In this case I just make a temporary folder called "to_convert", put the files in there, migrate, and then move them back. May want to include how to do this process since I would expect others will have the same question.

I don't find this to be convenient at all, I'd prefer to the add the option to the script to ran into a single file or an array of files, just like `exclude` but inverse.

2023-06-01 23:24 UTC, juliodialpad commented on migration_guide/Dialtone_8.md
> +```
> We may want to convey a little more that you probably shouldn't run the whole script on the entire codebase all at once, but do one section of the UI, visually verify it and fix any issues and then move on to the next.
> 
> Maybe the steps should be like..
> 
> Run the script on the desired files for the piece of UI you wish to change Verify the migration script changed files as expected Replace css variables with semantic visually verify the piece of UI you changed in light mode as well as dark mode, fix anything that is obviously off share preview with a designer and make any further requested changes make a PR to commit your changes repeat all this for the next section of UI

I like this steps, I'll add them to the process

2023-06-01 23:35 UTC, braddialpad commented on migration_guide/Dialtone_8.md
> +```
> I don't find this to be convenient at all, I'd prefer to the add the option to the script to ran into a single file or an array of files, just like `exclude` but inverse.

Yeah that definitely would be better.

2023-06-01 23:36 UTC, juliodialpad commented on migration_guide/Dialtone_8.md
> +```
Adding it

2023-06-02 01:00 UTC, braddialpad approved these changes
Fantastic thanks!

2023-06-02 01:00 UTC, merged