feat(stack): add defaults for align prop
dialpad/dialtone-legacy pull request #961
Opened 2023-10-02 15:34 UTC by ninamarina

## Description
https://dialpad.atlassian.net/browse/DLT-1265
Adds defaults for aligning items in the Stack component.
Documentation will be updated in the `dialtone-vue` repository.

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [ ] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

## Obligatory GIF (super important!)
![](path/to/gif)

2023-10-02 19:35 UTC, juliodialpad requested changes
I think we don't need to have those as utility classes.

I'd be better to just set those default values for row and column variants of the stack component.

And just say in the documentation that by default row stack will have `align-items: center` and column stack has `justify-content: flex-start` set by default.

2023-10-02 20:00 UTC, ninamarina commented
> I think we don't need to have those as utility classes.
> 
> I'd be better to just set those default values for row and column variants of the stack component.
> 
> And just say in the documentation that by default row stack will have `align-items: center` and column stack has `justify-content: flex-start` set by default.

Changed in 

> I think we don't need to have those as utility classes.
> 
> I'd be better to just set those default values for row and column variants of the stack component.
> 
> And just say in the documentation that by default row stack will have `align-items: center` and column stack has `justify-content: flex-start` set by default.

Changed in 3353c31b30dff7b8467815fd54323fee3038d21a

2023-10-03 14:51 UTC, iropolo commented on lib/build/less/components/stack.less
> +    align-items: normal;
`normal;` is the default value of `align-items` Is this adding value here?

2023-10-03 14:52 UTC, iropolo commented on lib/build/less/components/stack.less
> +    justify-content: normal;
is this `justify-content: normal;` css property doing some effect?

2023-10-03 14:55 UTC, iropolo approved these changes
pre-approving it.

Have some doubt on the use of `align-items: normal` and `justify-content: normal` but if it is intended to solve some issue or edge case would be cool to review it here, if it is not I would remove them.

Thanks,

2023-10-03 15:17 UTC, ninamarina commented on lib/build/less/components/stack.less
> +    justify-content: normal;
It's to override the default defined here https://github.com/dialpad/dialtone/pull/961/files#diff-a6abaef1f0bdd89f14149d49806e8d9d66c282871015d46657d8ff6b988a8566R55

2023-10-03 15:19 UTC, ninamarina commented on lib/build/less/components/stack.less
> +    align-items: normal;
Maybe for the `align-items` I don't need it, but I do for `justify-content`, so I thought for clarity and consistency add both

2023-10-03 15:26 UTC, iropolo commented on lib/build/less/components/stack.less
> +    justify-content: normal;
duh, right, didnt see it is under `&--row {` 👍🏼

2023-10-03 15:27 UTC, iropolo commented on lib/build/less/components/stack.less
> +    align-items: normal;
Would remove it if it is not adding value. 
in the other hand, `justify-content` is adding something necessary to work correctly.

2023-10-03 15:39 UTC, ninamarina commented on lib/build/less/components/stack.less
> +    align-items: normal;
I take your suggestion, let's have the less lines of css we can 👍

2023-10-03 16:09 UTC, braddialpad approved these changes
Looks good!

2023-10-03 18:50 UTC, juliodialpad approved these changes
Looking good, thanks Nina!

I'll create a ticket to improve this component, instead of using media queries for responsive versions we should be using our dialtone generators function but that's another story. I'll create the ticket and refer back to this PR.

2023-10-03 18:57 UTC, juliodialpad commented
Cleanup stack component ticket: https://dialpad.atlassian.net/browse/DLT-1270

2023-10-03 19:19 UTC, merged