fix(input-group): prevent label from spanning entire row
dialpad/dialtone-legacy pull request #975
Opened 2023-10-12 22:28 UTC by braddialpad

## Description

Fix requested for related product issue: https://dialpad.atlassian.net/browse/DP-82301

The radio button / checkbox labels were spanning the entire width of the container they were in making it possible to toggle a radio button by clicking wayyyy to the right of it in empty space.

Added new class to put on the fieldset that will correct these issues. Will need to make a change in dialtone vue to apply this class as well.

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

## Obligatory GIF (super important!)
![](https://media.giphy.com/media/KfTgl5LzZ4PzIZk0ot/giphy-downsized-large.gif)

2023-10-12 22:35 UTC, juliodialpad approved these changes
Nice, thanks for fixing this Brad!

2023-10-12 22:43 UTC, francisrupert requested changes
Watch out, changed rendering from stacked vertically to horizontally.

https://github.com/dialpad/dialtone/assets/1165933/bd1325da-c815-4517-ada4-69a566a56416

2023-10-13 15:56 UTC, juliodialpad commented
> Watch out, changed rendering from stacked vertically to horizontally.
> 
>  Screen.Recording.2023-10-12.at.5.41.24.PM.mov

I think that's because now the elements don't take up all the horizontal space (intended), If we want to maintain the examples as before, we need to update them to use `<dt-stack>`

2023-10-13 16:00 UTC, braddialpad commented
> Watch out, changed rendering from stacked vertically to horizontally.
> 
>  Screen.Recording.2023-10-12.at.5.41.24.PM.mov

Ah yes, this is because the radio/checkbox group pages are rendered using the vue components, and dialtone vue still needs to be updated to apply the new class. A very annoying issue we currently have, but will be fixed next quarter with the monorepo.

2023-10-13 16:00 UTC, braddialpad commented
I will just apply the class manually to these examples in the meantime

2023-10-16 18:26 UTC, merged